(function(){function d(a){throw a;}var g=void 0,i=!0,l=null,n=!1;function aa(){return function(a){return a}}function o(){return function(){}}function p(a){return function(b){this[a]=b}}function q(a){return function(){return this[a]}}function t(a){return function(){return a}}var v,w=w||{};w.global=this;w.xB=n;w.VO="en";w.gR=function(a){w.xI(a)};w.qR=function(a){w.xB||(a=a||"",d(Error("Importing test-only code into non-debug environment"+a?": "+a:".")))};
w.xI=function(a,b,c){a=a.split(".");c=c||w.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&w.sp(b)?c[e]=b:c=c[e]?c[e]:c[e]={}};w.LM=function(){for(var a=["window","event"],b=w.global,c;c=a.shift();)if(w.bN(b[c]))b=b[c];else return l;return b};w.AQ=function(a,b){var c=b||w.global,e;for(e in a)c[e]=a[e]};w.vP=o();w.FO=i;w.lR=o();w.IP="";w.lK=o();w.FQ=aa();w.qa=function(){d(Error("unimplemented abstract method"))};
w.wP=function(a){a.oQ=function(){return a.YM||(a.YM=new a)}};
w.Zj=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};w.sp=function(a){return a!==g};w.NQ=function(a){return a===l};w.bN=function(a){return a!=l};w.isArray=function(a){return"array"==w.Zj(a)};w.bf=function(a){var b=w.Zj(a);return"array"==b||"object"==b&&"number"==typeof a.length};w.LQ=function(a){return w.Kn(a)&&"function"==typeof a.getFullYear};w.Rc=function(a){return"string"==typeof a};w.$M=function(a){return"boolean"==typeof a};w.CJ=function(a){return"number"==typeof a};
w.ez=function(a){return"function"==w.Zj(a)};w.Kn=function(a){var b=typeof a;return"object"==b&&a!=l||"function"==b};w.wn=function(a){return a[w.Uw]||(a[w.Uw]=++w.XN)};w.IN=function(a){"removeAttribute"in a&&a.removeAttribute(w.Uw);try{delete a[w.Uw]}catch(b){}};w.Uw="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);w.XN=0;w.mQ=w.wn;w.jR=w.IN;w.SL=function(a){var b=w.Zj(a);if("object"==b||"array"==b){if(a.la)return a.la();var b="array"==b?[]:{},c;for(c in a)b[c]=w.SL(a[c]);return b}return a};
w.NL=function(a,b,c){return a.call.apply(a.bind,arguments)};w.ML=function(a,b,c){a||d(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};w.bind=function(a,b,c){w.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w.NL:w.ML;return w.bind.apply(l,arguments)};
w.uK=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};w.WQ=function(a,b){for(var c in b)a[c]=b[c]};w.now=Date.now||function(){return+new Date};
w.zQ=function(a){if(w.global.execScript)w.global.execScript(a,"JavaScript");else if(w.global.eval)if(w.gy==l&&(w.global.eval("var _et_ = 1;"),"undefined"!=typeof w.global._et_?(delete w.global._et_,w.gy=i):w.gy=n),w.gy)w.global.eval(a);else{var b=w.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=n;c.appendChild(b.createTextNode(a));b.body.appendChild(c);b.body.removeChild(c)}else d(Error("goog.globalEval not available"))};w.gy=l;
w.lQ=function(a,b){function c(a){return w.WH[a]||a}var e;e=w.WH?"BY_WHOLE"==w.bM?c:function(a){for(var a=a.split("-"),b=[],e=0;e<a.length;e++)b.push(c(a[e]));return b.join("-")}:aa();return b?a+"-"+e(b):e(a)};w.mR=function(a,b){w.WH=a;w.bM=b};w.rQ=function(a,b){var c=b||{},e;for(e in c)var f=(""+c[e]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f);return a};w.Rg=function(a,b){w.xI(a,b,g)};w.Q=function(a,b,c){a[b]=c};
w.e=function(a,b){function c(){}c.prototype=b.prototype;a.b=b.prototype;a.prototype=new c;a.prototype.constructor=a};w.HP=function(a,b,c){var e=arguments.callee.caller;if(e.b)return e.b.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),h=n,j=a.constructor;j;j=j.b&&j.b.constructor)if(j.prototype[b]===e)h=i;else if(h)return j.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,f);d(Error("goog.base called from a method of one name to a method of a different name"))};
w.scope=function(a){a.call(w.global)};w.debug={};function ba(a){this.stack=Error().stack||"";a&&(this.message=""+a)}w.e(ba,Error);ba.prototype.name="CustomError";w.P={};w.P.SN=function(a){return 0==a.lastIndexOf("/",0)};w.P.sM=function(a){var b=a.length-1;return 0<=b&&a.indexOf("/",b)==b};w.P.RP=function(a,b){return 0==w.P.xH(b,a.substr(0,b.length))};w.P.QP=function(a,b){return 0==w.P.xH(b,a.substr(a.length-b.length,b.length))};w.P.TN=function(a,b){for(var c=1;c<arguments.length;c++)var e=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a};w.P.VP=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};w.P.yi=function(a){return/^[\s\xa0]*$/.test(a)};
w.P.MQ=function(a){return w.P.yi(w.P.lN(a))};w.P.KQ=function(a){return!/[^\t\n\r ]/.test(a)};w.P.IQ=function(a){return!/[^a-zA-Z]/.test(a)};w.P.OQ=function(a){return!/[^0-9]/.test(a)};w.P.JQ=function(a){return!/[^a-zA-Z0-9]/.test(a)};w.P.QQ=function(a){return" "==a};w.P.RQ=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};w.P.vR=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};w.P.PP=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
w.P.$Q=function(a){return a.replace(/\xa0|\s/g," ")};w.P.ZQ=function(a){return a.replace(/\xa0|[ \t]+/g," ")};w.P.UP=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};w.P.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};w.P.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};w.P.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};w.P.xH=function(a,b){var c=(""+a).toLowerCase(),e=(""+b).toLowerCase();return c<e?-1:c==e?0:1};w.P.nK=/(\.\d+)|(\d+)|(\D+)/g;
w.P.aR=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(w.P.nK),e=b.toLowerCase().match(w.P.nK),f=Math.min(c.length,e.length),h=0;h<f;h++){var j=c[h],k=e[h];if(j!=k)return c=parseInt(j,10),!isNaN(c)&&(e=parseInt(k,10),!isNaN(e)&&c-e)?c-e:j<k?-1:1}return c.length!=e.length?c.length-e.length:a<b?-1:1};w.P.rM=/^[a-zA-Z0-9\-_.!~*'()]*$/;w.P.bt=function(a){a=""+a;return!w.P.rM.test(a)?encodeURIComponent(a):a};
w.P.hB=function(a){return decodeURIComponent(a.replace(/\+/g," "))};w.P.qN=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};w.P.gJ=function(a){if(!w.P.IL.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(w.P.JL,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(w.P.kN,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(w.P.SM,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(w.P.BN,"&quot;"));return a};w.P.JL=/&/g;w.P.kN=/</g;w.P.SM=/>/g;w.P.BN=/\"/g;w.P.IL=/[&<>\"]/;
w.P.lL=function(a){return w.P.contains(a,"&")?"document"in w.global?w.P.YN(a):w.P.ZN(a):a};w.P.YN=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(w.P.DL,function(a,f){var h=b[a];if(h)return h;if("#"==f.charAt(0)){var j=Number("0"+f.substr(1));isNaN(j)||(h=String.fromCharCode(j))}h||(c.innerHTML=a+" ",h=c.firstChild.nodeValue.slice(0,-1));return b[a]=h})};
w.P.ZN=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var e=Number("0"+c.substr(1));if(!isNaN(e))return String.fromCharCode(e)}return a}})};w.P.DL=/&([^;\s<&]+);?/g;w.P.IR=function(a,b){return w.P.qN(a.replace(/  /g," &#160;"),b)};
w.P.wR=function(a,b){for(var c=b.length,e=0;e<c;e++){var f=1==c?b:b.charAt(e);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};w.P.truncate=function(a,b,c){c&&(a=w.P.lL(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=w.P.gJ(a));return a};
w.P.CR=function(a,b,c,e){c&&(a=w.P.lL(a));if(e&&a.length>b)e>b&&(e=b),a=a.substring(0,b-e)+"..."+a.substring(a.length-e);else if(a.length>b)var e=Math.floor(b/2),f=a.length-e,a=a.substring(0,e+b%2)+"..."+a.substring(f);c&&(a=w.P.gJ(a));return a};w.P.tG={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};w.P.nz={"'":"\\'"};
w.P.quote=function(a){a=""+a;if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0);b[c+1]=w.P.tG[e]||(31<f&&127>f?e:w.P.tI(e))}b.push('"');return b.join("")};w.P.dQ=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=w.P.tI(a.charAt(c));return b.join("")};
w.P.tI=function(a){if(a in w.P.nz)return w.P.nz[a];if(a in w.P.tG)return w.P.nz[a]=w.P.tG[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return w.P.nz[a]=b};w.P.zR=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=i;return b};w.P.contains=function(a,b){return-1!=a.indexOf(b)};w.P.XP=function(a,b){return a&&b?a.split(b).length-1:0};
w.P.cA=function(a,b,c){var e=a;0<=b&&b<a.length&&0<c&&(e=a.substr(0,b)+a.substr(b+c,a.length-b-c));return e};w.P.remove=function(a,b){var c=RegExp(w.P.DK(b),"");return a.replace(c,"")};w.P.GK=function(a,b){var c=RegExp(w.P.DK(b),"g");return a.replace(c,"")};w.P.DK=function(a){return(""+a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};w.P.repeat=function(a,b){return Array(b+1).join(a)};
w.P.cR=function(a,b,c){a=w.sp(c)?a.toFixed(c):""+a;c=a.indexOf(".");-1==c&&(c=a.length);return w.P.repeat("0",Math.max(0,b-c))+a};w.P.lN=function(a){return a==l?"":""+a};w.P.OL=function(a){return Array.prototype.join.call(arguments,"")};w.P.WI=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^w.now()).toString(36)};
w.P.FH=function(a,b){for(var c=0,e=w.P.trim(""+a).split("."),f=w.P.trim(""+b).split("."),h=Math.max(e.length,f.length),j=0;0==c&&j<h;j++){var k=e[j]||"",m=f[j]||"",r=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var u=r.exec(k)||["","",""],x=s.exec(m)||["","",""];if(0==u[0].length&&0==x[0].length)break;c=w.P.pC(0==u[1].length?0:parseInt(u[1],10),0==x[1].length?0:parseInt(x[1],10))||w.P.pC(0==u[2].length,0==x[2].length)||w.P.pC(u[2],x[2])}while(0==c)}return c};
w.P.pC=function(a,b){return a<b?-1:a>b?1:0};w.P.CL=4294967296;w.P.DQ=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=w.P.CL;return b};w.P.aO=2147483648*Math.random()|0;w.P.ZP=function(){return"goog_"+w.P.aO++};w.P.AR=function(a){var b=Number(a);return 0==b&&w.P.yi(a)?NaN:b};w.P.hL={};w.P.yR=function(a){return w.P.hL[a]||(w.P.hL[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};w.P.iL={};
w.P.BR=function(a){return w.P.iL[a]||(w.P.iL[a]=(""+a).replace(/([A-Z])/g,"-$1").toLowerCase())};w.Zc={};w.Zc.pl=w.xB;function ca(a,b){b.unshift(a);ba.call(this,w.P.TN.apply(l,b));b.shift()}w.e(ca,ba);ca.prototype.name="AssertionError";w.Zc.dn=function(a,b,c,e){var f="Assertion failed";if(c)var f=f+(": "+c),h=e;else a&&(f+=": "+a,h=b);d(new ca(""+f,h||[]))};w.Zc.assert=function(a,b,c){w.Zc.pl&&!a&&w.Zc.dn("",l,b,Array.prototype.slice.call(arguments,2));return a};w.Zc.fQ=function(a,b){w.Zc.pl&&d(new ca("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
w.Zc.EP=function(a,b,c){w.Zc.pl&&!w.CJ(a)&&w.Zc.dn("Expected number but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.Zc.GP=function(a,b,c){w.Zc.pl&&!w.Rc(a)&&w.Zc.dn("Expected string but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.Zc.CP=function(a,b,c){w.Zc.pl&&!w.ez(a)&&w.Zc.dn("Expected function but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};
w.Zc.FP=function(a,b,c){w.Zc.pl&&!w.Kn(a)&&w.Zc.dn("Expected object but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.Zc.AP=function(a,b,c){w.Zc.pl&&!w.isArray(a)&&w.Zc.dn("Expected array but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.Zc.BP=function(a,b,c){w.Zc.pl&&!w.$M(a)&&w.Zc.dn("Expected boolean but got %s: %s.",[w.Zj(a),a],b,Array.prototype.slice.call(arguments,2));return a};
w.Zc.DP=function(a,b,c,e){w.Zc.pl&&!(a instanceof b)&&w.Zc.dn("instanceof check failed.",l,c,Array.prototype.slice.call(arguments,3))};w.T={};w.uo=i;w.T.dR=function(a){return a[a.length-1]};w.T.Sd=Array.prototype;w.T.indexOf=w.uo&&w.T.Sd.indexOf?function(a,b,c){return w.T.Sd.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(w.Rc(a))return!w.Rc(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
w.T.lastIndexOf=w.uo&&w.T.Sd.lastIndexOf?function(a,b,c){return w.T.Sd.lastIndexOf.call(a,b,c==l?a.length-1:c)}:function(a,b,c){c=c==l?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(w.Rc(a))return!w.Rc(b)||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};w.T.forEach=w.uo&&w.T.Sd.forEach?function(a,b,c){w.T.Sd.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.Rc(a)?a.split(""):a,h=0;h<e;h++)h in f&&b.call(c,f[h],h,a)};
w.T.wM=function(a,b){for(var c=a.length,e=w.Rc(a)?a.split(""):a,c=c-1;0<=c;--c)c in e&&b.call(g,e[c],c,a)};w.T.filter=w.uo&&w.T.Sd.filter?function(a,b,c){return w.T.Sd.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],h=0,j=w.Rc(a)?a.split(""):a,k=0;k<e;k++)if(k in j){var m=j[k];b.call(c,m,k,a)&&(f[h++]=m)}return f};
w.T.map=w.uo&&w.T.Sd.map?function(a,b,c){return w.T.Sd.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),h=w.Rc(a)?a.split(""):a,j=0;j<e;j++)j in h&&(f[j]=b.call(c,h[j],j,a));return f};w.T.reduce=function(a,b,c,e){if(a.reduce)return e?a.reduce(w.bind(b,e),c):a.reduce(b,c);var f=c;w.T.forEach(a,function(c,j){f=b.call(e,f,c,j,a)});return f};
w.T.reduceRight=function(a,b,c,e){if(a.reduceRight)return e?a.reduceRight(w.bind(b,e),c):a.reduceRight(b,c);var f=c;w.T.wM(a,function(c,j){f=b.call(e,f,c,j,a)});return f};w.T.some=w.uo&&w.T.Sd.some?function(a,b,c){return w.T.Sd.some.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.Rc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&b.call(c,f[h],h,a))return i;return n};
w.T.every=w.uo&&w.T.Sd.every?function(a,b,c){return w.T.Sd.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.Rc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&!b.call(c,f[h],h,a))return n;return i};w.T.find=function(a,b,c){b=w.T.BI(a,b,c);return 0>b?l:w.Rc(a)?a.charAt(b):a[b]};w.T.BI=function(a,b,c){for(var e=a.length,f=w.Rc(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&b.call(c,f[h],h,a))return h;return-1};w.T.gQ=function(a,b,c){b=w.T.tM(a,b,c);return 0>b?l:w.Rc(a)?a.charAt(b):a[b]};
w.T.tM=function(a,b,c){for(var e=a.length,f=w.Rc(a)?a.split(""):a,e=e-1;0<=e;e--)if(e in f&&b.call(c,f[e],e,a))return e;return-1};w.T.contains=function(a,b){return 0<=w.T.indexOf(a,b)};w.T.yi=function(a){return 0==a.length};w.T.clear=function(a){if(!w.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};w.T.GQ=function(a,b){w.T.contains(a,b)||a.push(b)};w.T.nJ=function(a,b,c){w.T.splice(a,c,0,b)};w.T.HQ=function(a,b,c){w.uK(w.T.splice,a,c,0).apply(l,b)};
w.T.insertBefore=function(a,b,c){var e;2==arguments.length||0>(e=w.T.indexOf(a,c))?a.push(b):w.T.nJ(a,b,e)};w.T.remove=function(a,b){var c=w.T.indexOf(a,b),e;(e=0<=c)&&w.T.cA(a,c);return e};w.T.cA=function(a,b){return 1==w.T.Sd.splice.call(a,b,1).length};w.T.kR=function(a,b,c){b=w.T.BI(a,b,c);return 0<=b?(w.T.cA(a,b),i):n};w.T.concat=function(a){return w.T.Sd.concat.apply(w.T.Sd,arguments)};w.T.la=function(a){if(w.isArray(a))return w.T.concat(a);for(var b=[],c=0,e=a.length;c<e;c++)b[c]=a[c];return b};
w.T.LG=function(a){return w.isArray(a)?w.T.concat(a):w.T.la(a)};w.T.extend=function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c],f;if(w.isArray(e)||(f=w.bf(e))&&e.hasOwnProperty("callee"))a.push.apply(a,e);else if(f)for(var h=a.length,j=e.length,k=0;k<j;k++)a[h+k]=e[k];else a.push(e)}};w.T.splice=function(a,b,c,e){return w.T.Sd.splice.apply(a,w.T.slice(arguments,1))};w.T.slice=function(a,b,c){return 2>=arguments.length?w.T.Sd.slice.call(a,b):w.T.Sd.slice.call(a,b,c)};
w.T.iR=function(a,b){for(var c=b||a,e={},f=0,h=0;h<a.length;){var j=a[h++],k=w.Kn(j)?"o"+w.wn(j):(typeof j).charAt(0)+j;Object.prototype.hasOwnProperty.call(e,k)||(e[k]=i,c[f++]=j)}c.length=f};w.T.pH=function(a,b,c){return w.T.qH(a,c||w.T.Qo,n,b)};w.T.LP=function(a,b,c){return w.T.qH(a,b,i,g,c)};w.T.qH=function(a,b,c,e,f){for(var h=0,j=a.length,k;h<j;){var m=h+j>>1,r;r=c?b.call(f,a[m],m,a):b(e,a[m]);0<r?h=m+1:(j=m,k=!r)}return k?h:~h};w.T.sort=function(a,b){w.T.Sd.sort.call(a,b||w.T.Qo)};
w.T.uR=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var e=b||w.T.Qo;w.T.sort(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};w.T.tR=function(a,b,c){var e=c||w.T.Qo;w.T.sort(a,function(a,c){return e(a[b],c[b])})};w.T.PQ=function(a,b,c){for(var b=b||w.T.Qo,e=1;e<a.length;e++){var f=b(a[e-1],a[e]);if(0<f||0==f&&c)return n}return i};
w.T.dD=function(a,b,c){if(!w.bf(a)||!w.bf(b)||a.length!=b.length)return n;for(var e=a.length,c=c||w.T.cM,f=0;f<e;f++)if(!c(a[f],b[f]))return n;return i};w.T.UL=function(a,b,c){return w.T.dD(a,b,c)};w.T.WP=function(a,b,c){for(var c=c||w.T.Qo,e=Math.min(a.length,b.length),f=0;f<e;f++){var h=c(a[f],b[f]);if(0!=h)return h}return w.T.Qo(a.length,b.length)};w.T.Qo=function(a,b){return a>b?1:a<b?-1:0};w.T.cM=function(a,b){return a===b};
w.T.JP=function(a,b,c){c=w.T.pH(a,b,c);return 0>c?(w.T.nJ(a,b,-(c+1)),i):n};w.T.KP=function(a,b,c){b=w.T.pH(a,b,c);return 0<=b?w.T.cA(a,b):n};w.T.MP=function(a,b){for(var c={},e=0;e<a.length;e++){var f=a[e],h=b(f,e,a);w.sp(h)&&(c[h]||(c[h]=[])).push(f)}return c};w.T.repeat=function(a,b){for(var c=[],e=0;e<b;e++)c[e]=a;return c};w.T.vM=function(a){for(var b=[],c=0;c<arguments.length;c++){var e=arguments[c];w.isArray(e)?b.push.apply(b,w.T.vM.apply(l,e)):b.push(e)}return b};
w.T.rotate=function(a,b){a.length&&(b%=a.length,0<b?w.T.Sd.unshift.apply(a,a.splice(-b,b)):0>b&&w.T.Sd.push.apply(a,a.splice(0,-b)));return a};w.T.JR=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var e=[],f=0;f<arguments.length;f++){var h=arguments[f];if(c>=h.length)return b;e.push(h[c])}b.push(e)}};w.T.sR=function(a,b){for(var c=b||Math.random,e=a.length-1;0<e;e--){var f=Math.floor(c()*(e+1)),h=a[e];a[e]=a[f];a[f]=h}};w.debug.Ye={};w.debug.HO=o();w.debug.Ye.xs=[];w.debug.Ye.gF=[];w.debug.Ye.aK=n;w.debug.Ye.EK=function(a){w.debug.Ye.xs[w.debug.Ye.xs.length]=a;if(w.debug.Ye.aK)for(var b=w.debug.Ye.gF,c=0;c<b.length;c++)a(w.bind(b[c].jO,b[c]))};w.debug.Ye.XQ=function(a){w.debug.Ye.aK=i;for(var b=w.bind(a.jO,a),c=0;c<w.debug.Ye.xs.length;c++)w.debug.Ye.xs[c](b);w.debug.Ye.gF.push(a)};w.debug.Ye.ER=function(a){for(var b=w.debug.Ye.gF,a=w.bind(a.GR,a),c=0;c<w.debug.Ye.xs.length;c++)w.debug.Ye.xs[c](a);b.length--};w.debug.cQ={zK:aa()};w.userAgent={};w.userAgent.$G=n;w.userAgent.ZG=n;w.userAgent.dH=n;w.userAgent.vB=n;w.userAgent.cH=n;w.userAgent.wL=n;w.userAgent.Dq=w.userAgent.$G||w.userAgent.ZG||w.userAgent.vB||w.userAgent.dH||w.userAgent.cH;w.userAgent.bJ=function(){return w.global.navigator?w.global.navigator.userAgent:l};w.userAgent.By=function(){return w.global.navigator};
w.userAgent.XM=function(){w.userAgent.lu=n;w.userAgent.dI=n;w.userAgent.Zx=n;w.userAgent.eI=n;w.userAgent.cI=n;var a;if(!w.userAgent.Dq&&(a=w.userAgent.bJ())){var b=w.userAgent.By();w.userAgent.lu=0==a.indexOf("Opera");w.userAgent.dI=!w.userAgent.lu&&-1!=a.indexOf("MSIE");w.userAgent.Zx=!w.userAgent.lu&&-1!=a.indexOf("WebKit");w.userAgent.eI=w.userAgent.Zx&&-1!=a.indexOf("Mobile");w.userAgent.cI=!w.userAgent.lu&&!w.userAgent.Zx&&"Gecko"==b.product}};w.userAgent.Dq||w.userAgent.XM();
w.userAgent.yB=w.userAgent.Dq?w.userAgent.cH:w.userAgent.lu;w.userAgent.bk=w.userAgent.Dq?w.userAgent.$G:w.userAgent.dI;w.userAgent.Sw=w.userAgent.Dq?w.userAgent.ZG:w.userAgent.cI;w.userAgent.Km=w.userAgent.Dq?w.userAgent.dH||w.userAgent.vB:w.userAgent.Zx;w.userAgent.$O=w.userAgent.vB||w.userAgent.eI;w.userAgent.iP=w.userAgent.Km;w.userAgent.jM=function(){var a=w.userAgent.By();return a&&a.platform||""};w.userAgent.zB=w.userAgent.jM();w.userAgent.bH=n;w.userAgent.eH=n;w.userAgent.aH=n;
w.userAgent.fH=n;w.userAgent.st=w.userAgent.bH||w.userAgent.eH||w.userAgent.aH||w.userAgent.fH;w.userAgent.WM=function(){w.userAgent.gM=w.P.contains(w.userAgent.zB,"Mac");w.userAgent.hM=w.P.contains(w.userAgent.zB,"Win");w.userAgent.fM=w.P.contains(w.userAgent.zB,"Linux");w.userAgent.iM=!!w.userAgent.By()&&w.P.contains(w.userAgent.By().appVersion||"","X11")};w.userAgent.st||w.userAgent.WM();w.userAgent.XO=w.userAgent.st?w.userAgent.bH:w.userAgent.gM;w.userAgent.tP=w.userAgent.st?w.userAgent.eH:w.userAgent.hM;
w.userAgent.TO=w.userAgent.st?w.userAgent.aH:w.userAgent.fM;w.userAgent.uP=w.userAgent.st?w.userAgent.fH:w.userAgent.iM;w.userAgent.kM=function(){var a="",b;w.userAgent.yB&&w.global.opera?(a=w.global.opera.version,a="function"==typeof a?a():a):(w.userAgent.Sw?b=/rv\:([^\);]+)(\)|;)/:w.userAgent.bk?b=/MSIE\s+([^\);]+)(\)|;)/:w.userAgent.Km&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(w.userAgent.bJ()))?a[1]:""));return w.userAgent.bk&&(b=w.userAgent.DM(),b>parseFloat(a))?""+b:a};
w.userAgent.DM=function(){var a=w.global.document;return a?a.documentMode:g};w.userAgent.VERSION=w.userAgent.kM();w.userAgent.UL=function(a,b){return w.P.FH(a,b)};w.userAgent.MJ={};w.userAgent.Ap=function(a){return w.userAgent.wL||w.userAgent.MJ[a]||(w.userAgent.MJ[a]=0<=w.P.FH(w.userAgent.VERSION,a))};w.userAgent.tJ={};w.userAgent.sJ=function(){return w.userAgent.tJ[9]||(w.userAgent.tJ[9]=w.userAgent.bk&&!!document.documentMode&&9<=document.documentMode)};w.w={};!w.userAgent.bk||w.userAgent.sJ();var ea=!w.userAgent.bk||w.userAgent.sJ(),fa=w.userAgent.bk&&!w.userAgent.Ap("8");!w.userAgent.Km||w.userAgent.Ap("528");w.userAgent.Sw&&w.userAgent.Ap("1.9b")||w.userAgent.bk&&w.userAgent.Ap("8")||w.userAgent.yB&&w.userAgent.Ap("9.5")||w.userAgent.Km&&w.userAgent.Ap("528");!w.userAgent.Sw||w.userAgent.Ap("8");w.lM={};w.lM.OO=o();function ga(){}ga.prototype.jI=n;ga.prototype.kj=function(){this.jI||(this.jI=i,this.cn())};ga.prototype.cn=function(){this.dM&&w.iI.apply(l,this.dM)};w.kj=function(a){a&&"function"==typeof a.kj&&a.kj()};w.iI=function(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b];w.bf(e)?w.iI.apply(l,e):w.kj(e)}};function ha(a,b){this.type=a;this.currentTarget=this.target=b}w.e(ha,ga);v=ha.prototype;v.cn=function(){delete this.type;delete this.target;delete this.currentTarget};v.cq=n;v.Tv=i;v.stopPropagation=function(){this.cq=i};v.preventDefault=function(){this.Tv=n};ha.stopPropagation=function(a){a.stopPropagation()};ha.preventDefault=function(a){a.preventDefault()};var y={wB:"click",yO:"dblclick",to:"mousedown",Eq:"mouseup",bi:"mouseover",ai:"mouseout",$h:"mousemove",lP:"selectstart",RO:"keypress",QO:"keydown",SO:"keyup",rO:"blur",JO:"focus",zO:"deactivate",KO:w.userAgent.bk?"focusin":"DOMFocusIn",LO:w.userAgent.bk?"focusout":"DOMFocusOut",tO:"change",kP:"select",mP:"submit",PO:"input",gP:"propertychange",DO:"dragstart",AO:"dragenter",CO:"dragover",BO:"dragleave",EO:"drop",qP:"touchstart",pP:"touchmove",oP:"touchend",nP:"touchcancel",vO:"contextmenu",GO:"error",
NO:"help",UO:"load",WO:"losecapture",hP:"readystatechange",Tw:"resize",jP:"scroll",sP:"unload",MO:"hashchange",cP:"pagehide",dP:"pageshow",fP:"popstate",wO:"copy",eP:"paste",xO:"cut",oO:"beforecopy",pO:"beforecut",qO:"beforepaste",YO:"message",uO:"connect",rP:w.userAgent.Km?"webkitTransitionEnd":w.userAgent.yB?"oTransitionEnd":"transitionend"};w.eq={};w.eq.object=function(a,b){return b};w.eq.qG=function(a){w.eq.qG[" "](a);return a};w.eq.qG[" "]=w.lK;w.eq.PL=function(a){try{return w.eq.qG(a.nodeName),i}catch(b){}return n};function ia(a,b){a&&this.kp(a,b)}w.e(ia,ha);v=ia.prototype;v.target=l;v.relatedTarget=l;v.offsetX=0;v.offsetY=0;v.clientX=0;v.clientY=0;v.screenX=0;v.screenY=0;v.button=0;v.keyCode=0;v.charCode=0;v.ctrlKey=n;v.altKey=n;v.shiftKey=n;v.metaKey=n;v.mr=l;
v.kp=function(a,b){var c=this.type=a.type;ha.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?w.userAgent.Sw&&(w.eq.PL(e)||(e=l)):c==y.bi?e=a.fromElement:c==y.ai&&(e=a.toElement);this.relatedTarget=e;this.offsetX=w.userAgent.Km||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=w.userAgent.Km||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.mr=a;delete this.Tv;delete this.cq};v.stopPropagation=function(){ia.b.stopPropagation.call(this);this.mr.stopPropagation?this.mr.stopPropagation():this.mr.cancelBubble=i};
v.preventDefault=function(){ia.b.preventDefault.call(this);var a=this.mr;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,fa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};v.cn=function(){ia.b.cn.call(this);this.relatedTarget=this.currentTarget=this.target=this.mr=l};w.w.hH=o();w.w.hH.prototype.Va=o();w.w.hH.prototype.bc=o();function ja(){}var ka=0;v=ja.prototype;v.key=0;v.fq=n;v.eC=n;v.kp=function(a,b,c,e,f,h){w.ez(a)?this.xJ=i:a&&a.handleEvent&&w.ez(a.handleEvent)?this.xJ=n:d(Error("Invalid listener argument"));this.hs=a;this.AK=b;this.src=c;this.type=e;this.capture=!!f;this.Oy=h;this.eC=n;this.key=++ka;this.fq=n};v.handleEvent=function(a){return this.xJ?this.hs.call(this.Oy||this.src,a):this.hs.handleEvent.call(this.hs,a)};w.object={};w.object.forEach=function(a,b,c){for(var e in a)b.call(c,a[e],e,a)};w.object.filter=function(a,b,c){var e={},f;for(f in a)b.call(c,a[f],f,a)&&(e[f]=a[f]);return e};w.object.map=function(a,b,c){var e={},f;for(f in a)e[f]=b.call(c,a[f],f,a);return e};w.object.some=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return i;return n};w.object.every=function(a,b,c){for(var e in a)if(!b.call(c,a[e],e,a))return n;return i};w.object.sn=function(a){var b=0,c;for(c in a)b++;return b};
w.object.jQ=function(a){for(var b in a)return b};w.object.kQ=function(a){for(var b in a)return a[b]};w.object.contains=function(a,b){return w.object.er(a,b)};w.object.Ff=function(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b};w.object.mg=function(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b};w.object.yQ=function(a,b){for(var c=w.bf(b),e=c?b:arguments,c=c?0:1;c<e.length&&!(a=a[e[c]],!w.sp(a));c++);return a};w.object.pk=function(a,b){return b in a};
w.object.er=function(a,b){for(var c in a)if(a[c]==b)return i;return n};w.object.uM=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return e};w.object.hQ=function(a,b,c){return(b=w.object.uM(a,b,c))&&a[b]};w.object.yi=function(a){for(var b in a)return n;return i};w.object.clear=function(a){for(var b in a)delete a[b]};w.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};
w.object.add=function(a,b,c){b in a&&d(Error('The object already contains the key "'+b+'"'));w.object.set(a,b,c)};w.object.get=function(a,b,c){return b in a?a[b]:c};w.object.set=function(a,b,c){a[b]=c};w.object.pR=function(a,b,c){return b in a?a[b]:a[b]=c};w.object.la=function(a){var b={},c;for(c in a)b[c]=a[c];return b};w.object.bO=function(a){var b=w.Zj(a);if("object"==b||"array"==b){if(a.la)return a.la();var b="array"==b?[]:{},c;for(c in a)b[c]=w.object.bO(a[c]);return b}return a};
w.object.WN=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};w.object.iH="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");w.object.extend=function(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var h=0;h<w.object.iH.length;h++)c=w.object.iH[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};
w.object.create=function(a){var b=arguments.length;if(1==b&&w.isArray(arguments[0]))return w.object.create.apply(l,arguments[0]);b%2&&d(Error("Uneven number of arguments"));for(var c={},e=0;e<b;e+=2)c[arguments[e]]=arguments[e+1];return c};w.object.ZL=function(a){var b=arguments.length;if(1==b&&w.isArray(arguments[0]))return w.object.ZL.apply(l,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=i;return c};w.w.nO=n;w.w.ce={};w.w.Zg={};w.w.fl={};w.w.wN="on";w.w.tF={};w.w.SQ="_";
w.w.Va=function(a,b,c,e,f){if(b){if(w.isArray(b)){for(var h=0;h<b.length;h++)w.w.Va(a,b[h],c,e,f);return l}var e=!!e,j=w.w.Zg;b in j||(j[b]={Cc:0,Ii:0});j=j[b];e in j||(j[e]={Cc:0,Ii:0},j.Cc++);var j=j[e],k=w.wn(a),m;j.Ii++;if(j[k]){m=j[k];for(h=0;h<m.length;h++)if(j=m[h],j.hs==c&&j.Oy==f){if(j.fq)break;return m[h].key}}else m=j[k]=[],j.Cc++;h=w.w.PM();h.src=a;j=new ja;j.kp(c,h,a,b,e,f);c=j.key;h.key=c;m.push(j);w.w.ce[c]=j;w.w.fl[k]||(w.w.fl[k]=[]);w.w.fl[k].push(j);a.addEventListener?(a==w.global||
!a.XH)&&a.addEventListener(b,h,e):a.attachEvent(w.w.SI(b),h);return c}d(Error("Invalid event type"))};w.w.PM=function(){var a=w.w.Nu,b=ea?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b};w.w.iN=function(a,b,c,e,f){if(w.isArray(b))for(var h=0;h<b.length;h++)w.w.iN(a,b[h],c,e,f);else a=w.w.Va(a,b,c,e,f),w.w.ce[a].eC=i};w.w.TQ=function(a,b,c,e,f){b.Va(a,c,e,f)};
w.w.bc=function(a,b,c,e,f){if(w.isArray(b)){for(var h=0;h<b.length;h++)w.w.bc(a,b[h],c,e,f);return l}e=!!e;a=w.w.ED(a,b,e);if(!a)return n;for(h=0;h<a.length;h++)if(a[h].hs==c&&a[h].capture==e&&a[h].Oy==f)return w.w.eB(a[h].key);return n};
w.w.eB=function(a){if(!w.w.ce[a])return n;var b=w.w.ce[a];if(b.fq)return n;var c=b.src,e=b.type,f=b.AK,h=b.capture;c.removeEventListener?(c==w.global||!c.XH)&&c.removeEventListener(e,f,h):c.detachEvent&&c.detachEvent(w.w.SI(e),f);c=w.wn(c);f=w.w.Zg[e][h][c];if(w.w.fl[c]){var j=w.w.fl[c];w.T.remove(j,b);0==j.length&&delete w.w.fl[c]}b.fq=i;f.jK=i;w.w.CH(e,h,c,f);delete w.w.ce[a];return i};w.w.DR=function(a,b,c,e,f){b.bc(a,c,e,f)};
w.w.CH=function(a,b,c,e){if(!e.tz&&e.jK){for(var f=0,h=0;f<e.length;f++)e[f].fq?e[f].AK.src=l:(f!=h&&(e[h]=e[f]),h++);e.length=h;e.jK=n;0==h&&(delete w.w.Zg[a][b][c],w.w.Zg[a][b].Cc--,0==w.w.Zg[a][b].Cc&&(delete w.w.Zg[a][b],w.w.Zg[a].Cc--),0==w.w.Zg[a].Cc&&delete w.w.Zg[a])}};
w.w.GK=function(a,b,c){var e=0,f=b==l,h=c==l,c=!!c;if(a==l)w.object.forEach(w.w.fl,function(a){for(var j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(h||c==k.capture))w.w.eB(k.key),e++}});else if(a=w.wn(a),w.w.fl[a])for(var a=w.w.fl[a],j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(h||c==k.capture))w.w.eB(k.key),e++}return e};w.w.qQ=function(a,b,c){return w.w.ED(a,b,c)||[]};w.w.ED=function(a,b,c){var e=w.w.Zg;return b in e&&(e=e[b],c in e&&(e=e[c],a=w.wn(a),e[a]))?e[a]:l};
w.w.pQ=function(a,b,c,e,f){e=!!e;if(a=w.w.ED(a,b,e))for(b=0;b<a.length;b++)if(!a[b].fq&&a[b].hs==c&&a[b].capture==e&&a[b].Oy==f)return a[b];return l};w.w.BQ=function(a,b,c){var a=w.wn(a),e=w.w.fl[a];if(e){var f=w.sp(b),h=w.sp(c);return f&&h?(e=w.w.Zg[b],!!e&&!!e[c]&&a in e[c]):!f&&!h?i:w.T.some(e,function(a){return f&&a.type==b||h&&a.capture==c})}return n};w.w.eQ=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
w.w.SI=function(a){return a in w.w.tF?w.w.tF[a]:w.w.tF[a]=w.w.wN+a};w.w.iQ=function(a,b,c,e){var f=w.w.Zg;return b in f&&(f=f[b],c in f)?w.w.qr(f[c],a,b,c,e):i};w.w.qr=function(a,b,c,e,f){var h=1,b=w.wn(b);if(a[b]){a.Ii--;a=a[b];a.tz?a.tz++:a.tz=1;try{for(var j=a.length,k=0;k<j;k++){var m=a[k];m&&!m.fq&&(h&=w.w.kD(m,f)!==n)}}finally{a.tz--,w.w.CH(c,e,b,a)}}return Boolean(h)};w.w.kD=function(a,b){var c=a.handleEvent(b);a.eC&&w.w.eB(a.key);return c};w.w.wQ=function(){return w.object.sn(w.w.ce)};
w.w.dispatchEvent=function(a,b){var c=b.type||b,e=w.w.Zg;if(!(c in e))return i;if(w.Rc(b))b=new ha(b,a);else if(b instanceof ha)b.target=b.target||a;else{var f=b,b=new ha(c,a);w.object.extend(b,f)}var f=1,h,e=e[c],c=i in e,j;if(c){h=[];for(j=a;j;j=j.AF)h.push(j);j=e[i];j.Ii=j.Cc;for(var k=h.length-1;!b.cq&&0<=k&&j.Ii;k--)b.currentTarget=h[k],f&=w.w.qr(j,h[k],b.type,i,b)&&b.Tv!=n}if(n in e)if(j=e[n],j.Ii=j.Cc,c)for(k=0;!b.cq&&k<h.length&&j.Ii;k++)b.currentTarget=h[k],f&=w.w.qr(j,h[k],b.type,n,b)&&
b.Tv!=n;else for(e=a;!b.cq&&e&&j.Ii;e=e.AF)b.currentTarget=e,f&=w.w.qr(j,e,b.type,n,b)&&b.Tv!=n;return Boolean(f)};w.w.eR=function(a){w.w.Nu=a.zK(w.w.Nu)};
w.w.Nu=function(a,b){if(!w.w.ce[a])return i;var c=w.w.ce[a],e=c.type,f=w.w.Zg;if(!(e in f))return i;var f=f[e],h,j;if(!ea){h=b||w.LM();var k=i in f,m=n in f;if(k){if(w.w.dN(h))return i;w.w.nN(h)}var r=new ia;r.kp(h,this);h=i;try{if(k){for(var s=[],u=r.currentTarget;u;u=u.parentNode)s.push(u);j=f[i];j.Ii=j.Cc;for(var x=s.length-1;!r.cq&&0<=x&&j.Ii;x--)r.currentTarget=s[x],h&=w.w.qr(j,s[x],e,i,r);if(m){j=f[n];j.Ii=j.Cc;for(x=0;!r.cq&&x<s.length&&j.Ii;x++)r.currentTarget=s[x],h&=w.w.qr(j,s[x],e,n,r)}}else h=
w.w.kD(c,r)}finally{s&&(s.length=0),r.kj()}return h}e=new ia(b,this);try{h=w.w.kD(c,e)}finally{e.kj()}return h};w.w.nN=function(a){var b=n;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=i}if(b||a.returnValue==g)a.returnValue=i};w.w.dN=function(a){return 0>a.keyCode||a.returnValue!=g};w.w.$N=0;w.w.xQ=function(a){return a+"_"+w.w.$N++};w.debug.Ye.EK(function(a){w.w.Nu=a(w.w.Nu)});function la(){}w.e(la,ga);v=la.prototype;v.XH=i;v.AF=l;v.addEventListener=function(a,b,c,e){w.w.Va(this,a,b,c,e)};v.removeEventListener=function(a,b,c,e){w.w.bc(this,a,b,c,e)};v.dispatchEvent=function(a){return w.w.dispatchEvent(this,a)};v.cn=function(){la.b.cn.call(this);w.w.GK(this);this.AF=l};var ma=w.global.window;w.dv={};w.dv.fN=function(a){return/^\s*$/.test(a)?n:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};w.dv.parse=function(a){a=""+a;if(w.dv.fN(a))try{return eval("("+a+")")}catch(b){}d(Error("Invalid JSON string: "+a))};w.dv.FR=function(a){return eval("("+a+")")};w.dv.Wa=function(a,b){return(new na(b)).Wa(a)};
function na(a){this.dA=a}na.prototype.Wa=function(a){var b=[];oa(this,a,b);return b.join("")};
function oa(a,b,c){switch(typeof b){case "string":pa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(w.isArray(b)){var e=b.length;c.push("[");for(var f="",h=0;h<e;h++)c.push(f),f=b[h],oa(a,a.dA?a.dA.call(b,""+h,f):f,c),f=",";c.push("]");break}c.push("{");e="";for(h in b)Object.prototype.hasOwnProperty.call(b,h)&&(f=b[h],"function"!=typeof f&&(c.push(e),pa(h,c),
c.push(":"),oa(a,a.dA?a.dA.call(b,h,f):f,c),e=","));c.push("}");break;case "function":break;default:d(Error("Unknown type: "+typeof b))}}var ra={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},sa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function pa(a,b){b.push('"',a.replace(sa,function(a){if(a in ra)return ra[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return ra[a]=f+b.toString(16)}),'"')};w.zj={};function ta(){}ta.prototype.uH=l;ta.prototype.Hu=function(){var a;if(!(a=this.uH))a={},ua(this)&&(a[0]=i,a[1]=i),a=this.uH=a;return a};function va(a,b){this.kO=a;this.zN=b}w.e(va,ta);va.prototype.uC=function(){return this.kO()};va.prototype.Hu=function(){return this.zN()};w.zj.ck=function(){return w.zj.ck.zI.uC()};w.zj.ck.Hu=function(){return w.zj.ck.zI.Hu()};w.zj.ck.nR=function(a,b){w.zj.ck.PK(new va(a,b))};w.zj.ck.PK=function(a){w.zj.ck.zI=a};function wa(){}w.e(wa,ta);wa.prototype.uC=function(){var a=ua(this);return a?new ActiveXObject(a):new XMLHttpRequest};wa.prototype.jE=l;
function ua(a){if(!a.jE&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var e=b[c];try{return new ActiveXObject(e),a.jE=e}catch(f){}}d(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.jE}w.zj.ck.PK(new wa);w.Ed={};w.Ed.sn=function(a){return"function"==typeof a.sn?a.sn():w.bf(a)||w.Rc(a)?a.length:w.object.sn(a)};w.Ed.Ff=function(a){if("function"==typeof a.Ff)return a.Ff();if(w.Rc(a))return a.split("");if(w.bf(a)){for(var b=[],c=a.length,e=0;e<c;e++)b.push(a[e]);return b}return w.object.Ff(a)};w.Ed.mg=function(a){if("function"==typeof a.mg)return a.mg();if("function"!=typeof a.Ff){if(w.bf(a)||w.Rc(a)){for(var b=[],a=a.length,c=0;c<a;c++)b.push(c);return b}return w.object.mg(a)}};
w.Ed.contains=function(a,b){return"function"==typeof a.contains?a.contains(b):"function"==typeof a.er?a.er(b):w.bf(a)||w.Rc(a)?w.T.contains(a,b):w.object.er(a,b)};w.Ed.yi=function(a){return"function"==typeof a.yi?a.yi():w.bf(a)||w.Rc(a)?w.T.yi(a):w.object.yi(a)};w.Ed.clear=function(a){"function"==typeof a.clear?a.clear():w.bf(a)?w.T.clear(a):w.object.clear(a)};
w.Ed.forEach=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(w.bf(a)||w.Rc(a))w.T.forEach(a,b,c);else for(var e=w.Ed.mg(a),f=w.Ed.Ff(a),h=f.length,j=0;j<h;j++)b.call(c,f[j],e&&e[j],a)};w.Ed.filter=function(a,b,c){if("function"==typeof a.filter)return a.filter(b,c);if(w.bf(a)||w.Rc(a))return w.T.filter(a,b,c);var e,f=w.Ed.mg(a),h=w.Ed.Ff(a),j=h.length;if(f){e={};for(var k=0;k<j;k++)b.call(c,h[k],f[k],a)&&(e[f[k]]=h[k])}else{e=[];for(k=0;k<j;k++)b.call(c,h[k],g,a)&&e.push(h[k])}return e};
w.Ed.map=function(a,b,c){if("function"==typeof a.map)return a.map(b,c);if(w.bf(a)||w.Rc(a))return w.T.map(a,b,c);var e,f=w.Ed.mg(a),h=w.Ed.Ff(a),j=h.length;if(f){e={};for(var k=0;k<j;k++)e[f[k]]=b.call(c,h[k],f[k],a)}else{e=[];for(k=0;k<j;k++)e[k]=b.call(c,h[k],g,a)}return e};w.Ed.some=function(a,b,c){if("function"==typeof a.some)return a.some(b,c);if(w.bf(a)||w.Rc(a))return w.T.some(a,b,c);for(var e=w.Ed.mg(a),f=w.Ed.Ff(a),h=f.length,j=0;j<h;j++)if(b.call(c,f[j],e&&e[j],a))return i;return n};
w.Ed.every=function(a,b,c){if("function"==typeof a.every)return a.every(b,c);if(w.bf(a)||w.Rc(a))return w.T.every(a,b,c);for(var e=w.Ed.mg(a),f=w.Ed.Ff(a),h=f.length,j=0;j<h;j++)if(!b.call(c,f[j],e&&e[j],a))return n;return i};w.sb={};w.sb.Of="StopIteration"in w.global?w.global.StopIteration:Error("StopIteration");function xa(){}xa.prototype.next=function(){d(w.sb.Of)};xa.prototype.AB=function(){return this};w.sb.Vh=function(a){if(a instanceof xa)return a;if("function"==typeof a.AB)return a.AB(n);if(w.bf(a)){var b=0,c=new xa;c.next=function(){for(;;){b>=a.length&&d(w.sb.Of);if(b in a)return a[b++];b++}};return c}d(Error("Not implemented"))};
w.sb.forEach=function(a,b,c){if(w.bf(a))try{w.T.forEach(a,b,c)}catch(e){e!==w.sb.Of&&d(e)}else{a=w.sb.Vh(a);try{for(;;)b.call(c,a.next(),g,a)}catch(f){f!==w.sb.Of&&d(f)}}};w.sb.filter=function(a,b,c){var a=w.sb.Vh(a),e=new xa;e.next=function(){for(;;){var e=a.next();if(b.call(c,e,g,a))return e}};return e};
w.sb.hR=function(a,b,c){var e=0,f=a,h=c||1;1<arguments.length&&(e=a,f=b);0==h&&d(Error("Range step argument must not be zero"));var j=new xa;j.next=function(){(h>0&&e>=f||h<0&&e<=f)&&d(w.sb.Of);var a=e;e=e+h;return a};return j};w.sb.join=function(a,b){return w.sb.LG(a).join(b)};w.sb.map=function(a,b,c){var a=w.sb.Vh(a),e=new xa;e.next=function(){for(;;){var e=a.next();return b.call(c,e,g,a)}};return e};w.sb.reduce=function(a,b,c,e){var f=c;w.sb.forEach(a,function(a){f=b.call(e,f,a)});return f};
w.sb.some=function(a,b,c){a=w.sb.Vh(a);try{for(;;)if(b.call(c,a.next(),g,a))return i}catch(e){e!==w.sb.Of&&d(e)}return n};w.sb.every=function(a,b,c){a=w.sb.Vh(a);try{for(;;)if(!b.call(c,a.next(),g,a))return n}catch(e){e!==w.sb.Of&&d(e)}return i};w.sb.SP=function(a){var b=arguments,c=b.length,e=0,f=new xa;f.next=function(){try{return e>=c&&d(w.sb.Of),w.sb.Vh(b[e]).next()}catch(a){return(a!==w.sb.Of||e>=c)&&d(a),e++,this.next()}};return f};
w.sb.bQ=function(a,b,c){var a=w.sb.Vh(a),e=new xa,f=i;e.next=function(){for(;;){var e=a.next();if(!f||!b.call(c,e,g,a))return f=n,e}};return e};w.sb.xR=function(a,b,c){var a=w.sb.Vh(a),e=new xa,f=i;e.next=function(){for(;;)if(f){var e=a.next();if(b.call(c,e,g,a))return e;f=n}else d(w.sb.Of)};return e};w.sb.LG=function(a){if(w.bf(a))return w.T.LG(a);var a=w.sb.Vh(a),b=[];w.sb.forEach(a,function(a){b.push(a)});return b};
w.sb.dD=function(a,b){var a=w.sb.Vh(a),b=w.sb.Vh(b),c,e;try{for(;;){c=e=n;var f=a.next();c=i;var h=b.next();e=i;if(f!=h)break}}catch(j){j!==w.sb.Of&&d(j);if(c&&!e)return n;if(!e)try{b.next()}catch(k){return k!==w.sb.Of&&d(k),i}}return n};w.sb.YQ=function(a,b){try{return w.sb.Vh(a).next()}catch(c){return c!=w.sb.Of&&d(c),b}};
w.sb.product=function(a){if(w.T.some(arguments,function(a){return!a.length})||!arguments.length)return new xa;var b=new xa,c=arguments,e=w.T.repeat(0,c.length);b.next=function(){if(e){for(var a=w.T.map(e,function(a,b){return c[b][a]}),b=e.length-1;0<=b;b--){if(e[b]<c[b].length-1){e[b]++;break}if(0==b){e=l;break}e[b]=0}return a}d(w.sb.Of)};return b};
w.sb.$P=function(a){var b=w.sb.Vh(a),c=[],e=0,a=new xa,f=n;a.next=function(){var a=l;if(!f)try{return a=b.next(),c.push(a),a}catch(j){(j!=w.sb.Of||w.T.yi(c))&&d(j),f=i}a=c[e];e=(e+1)%c.length;return a};return a};function ya(a,b){this.ah={};this.Ua=[];var c=arguments.length;if(1<c){c%2&&d(Error("Uneven number of arguments"));for(var e=0;e<c;e+=2)this.set(arguments[e],arguments[e+1])}else if(a){a instanceof ya?(c=a.mg(),e=a.Ff()):(c=w.object.mg(a),e=w.object.Ff(a));for(var f=0;f<c.length;f++)this.set(c[f],e[f])}}v=ya.prototype;v.Cc=0;v.Mw=0;v.sn=q("Cc");v.Ff=function(){za(this);for(var a=[],b=0;b<this.Ua.length;b++)a.push(this.ah[this.Ua[b]]);return a};v.mg=function(){za(this);return this.Ua.concat()};
v.pk=function(a){return Aa(this.ah,a)};v.er=function(a){for(var b=0;b<this.Ua.length;b++){var c=this.Ua[b];if(Aa(this.ah,c)&&this.ah[c]==a)return i}return n};v.dD=function(a,b){if(this===a)return i;if(this.Cc!=a.sn())return n;var c=b||Ba;za(this);for(var e,f=0;e=this.Ua[f];f++)if(!c(this.get(e),a.get(e)))return n;return i};function Ba(a,b){return a===b}v.yi=function(){return 0==this.Cc};v.clear=function(){this.ah={};this.Mw=this.Cc=this.Ua.length=0};
v.remove=function(a){return Aa(this.ah,a)?(delete this.ah[a],this.Cc--,this.Mw++,this.Ua.length>2*this.Cc&&za(this),i):n};function za(a){if(a.Cc!=a.Ua.length){for(var b=0,c=0;b<a.Ua.length;){var e=a.Ua[b];Aa(a.ah,e)&&(a.Ua[c++]=e);b++}a.Ua.length=c}if(a.Cc!=a.Ua.length){for(var f={},c=b=0;b<a.Ua.length;)e=a.Ua[b],Aa(f,e)||(a.Ua[c++]=e,f[e]=1),b++;a.Ua.length=c}}v.get=function(a,b){return Aa(this.ah,a)?this.ah[a]:b};
v.set=function(a,b){Aa(this.ah,a)||(this.Cc++,this.Ua.push(a),this.Mw++);this.ah[a]=b};v.la=function(){return new ya(this)};v.WN=function(){for(var a=new ya,b=0;b<this.Ua.length;b++){var c=this.Ua[b];a.set(this.ah[c],c)}return a};v.AB=function(a){za(this);var b=0,c=this.Ua,e=this.ah,f=this.Mw,h=this,j=new xa;j.next=function(){for(;;){f!=h.Mw&&d(Error("The map has changed since the iterator was created"));b>=c.length&&d(w.sb.Of);var j=c[b++];return a?j:e[j]}};return j};
function Aa(a,b){return Object.prototype.hasOwnProperty.call(a,b)};w.uri={};w.uri.L={};w.uri.L.rH=function(a,b,c,e,f,h,j){var k=[];a&&k.push(a,":");c&&(k.push("//"),b&&k.push(b,"@"),k.push(c),e&&k.push(":",e));f&&k.push(f);h&&k.push("?",h);j&&k.push("#",j);return k.join("")};w.uri.L.RN=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");w.uri.L.split=function(a){return a.match(w.uri.L.RN)};w.uri.L.Sx=function(a){return a&&decodeURIComponent(a)};
w.uri.L.zr=function(a,b){return w.uri.L.split(b)[a]||l};w.uri.L.QD=function(a){return w.uri.L.zr(1,a)};w.uri.L.FM=function(a){a=w.uri.L.QD(a);!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""};w.uri.L.RM=function(a){return w.uri.L.zr(2,a)};w.uri.L.cJ=function(a){return w.uri.L.Sx(w.uri.L.RM(a))};w.uri.L.EM=function(a){return w.uri.L.zr(3,a)};w.uri.L.KI=function(a){return w.uri.L.Sx(w.uri.L.EM(a))};
w.uri.L.LD=function(a){return Number(w.uri.L.zr(4,a))||l};w.uri.L.OM=function(a){return w.uri.L.zr(5,a)};w.uri.L.Iu=function(a){return w.uri.L.Sx(w.uri.L.OM(a))};w.uri.L.VI=function(a){return w.uri.L.zr(6,a)};w.uri.L.HM=function(a){var b=a.indexOf("#");return 0>b?l:a.substr(b+1)};w.uri.L.oR=function(a,b){return w.uri.L.GN(a)+(b?"#"+b:"")};w.uri.L.MI=function(a){return w.uri.L.Sx(w.uri.L.HM(a))};w.uri.L.nQ=function(a){a=w.uri.L.split(a);return w.uri.L.rH(a[1],a[2],a[3],a[4])};
w.uri.L.vQ=function(a){a=w.uri.L.split(a);return w.uri.L.rH(l,l,l,l,a[5],a[6],a[7])};w.uri.L.GN=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};w.uri.L.EQ=function(a,b){var c=w.uri.L.split(a),e=w.uri.L.split(b);return c[3]==e[3]&&c[1]==e[1]&&c[4]==e[4]};w.uri.L.LL=function(a){w.xB&&(0<=a.indexOf("#")||0<=a.indexOf("?"))&&d(Error("goog.uri.utils: Fragment or query identifiers are not supported: ["+a+"]"))};
w.uri.L.DB=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=g)}return a.join("")};w.uri.L.lH=function(a,b,c){if(w.isArray(b))for(var e=0;e<b.length;e++)c.push("&",a),""!==b[e]&&c.push("=",w.P.bt(b[e]));else b!=l&&(c.push("&",a),""!==b&&c.push("=",w.P.bt(b)))};w.uri.L.VB=function(a,b,c){for(c=c||0;c<b.length;c+=2)w.uri.L.lH(b[c],b[c+1],a);return a};
w.uri.L.NP=function(a,b){var c=w.uri.L.VB([],a,b);c[0]="";return c.join("")};w.uri.L.sH=function(a,b){for(var c in b)w.uri.L.lH(c,b[c],a);return a};w.uri.L.OP=function(a){a=w.uri.L.sH([],a);a[0]="";return a.join("")};w.uri.L.xP=function(a,b){return w.uri.L.DB(2==arguments.length?w.uri.L.VB([a],arguments[1],0):w.uri.L.VB([a],arguments,1))};w.uri.L.yP=function(a,b){return w.uri.L.DB(w.uri.L.sH([a],b))};w.uri.L.KL=function(a,b){return w.uri.L.DB([a,"&","zx","=",w.P.bt(b)])};
w.uri.L.my=function(a,b,c,e){for(var f=c.length;0<=(b=a.indexOf(c,b))&&b<e;){var h=a.charCodeAt(b-1);if(38==h||63==h)if(h=a.charCodeAt(b+f),!h||61==h||38==h||35==h)return b;b+=f+1}return-1};w.uri.L.Py=/#|$/;w.uri.L.CQ=function(a,b){return 0<=w.uri.L.my(a,0,b,a.search(w.uri.L.Py))};w.uri.L.tQ=function(a,b){var c=a.search(w.uri.L.Py),e=w.uri.L.my(a,0,b,c);if(0>e)return l;var f=a.indexOf("&",e);if(0>f||f>c)f=c;e+=b.length+1;return w.P.hB(a.substr(e,f-e))};
w.uri.L.uQ=function(a,b){for(var c=a.search(w.uri.L.Py),e=0,f,h=[];0<=(f=w.uri.L.my(a,e,b,c));){e=a.indexOf("&",f);if(0>e||e>c)e=c;f+=b.length+1;h.push(w.P.hB(a.substr(f,e-f)))}return h};w.uri.L.VN=/[?&]($|#)/;w.uri.L.HN=function(a){for(var b=a.search(w.uri.L.Py),c=0,e,f=[];0<=(e=w.uri.L.my(a,c,"zx",b));)f.push(a.substring(c,e)),c=Math.min(a.indexOf("&",e)+1||b,b);f.push(a.substr(c));return f.join("").replace(w.uri.L.VN,"$1")};
w.uri.L.PN=function(a){var b=w.P.WI();return w.uri.L.KL(w.uri.L.HN(a),b)};w.uri.L.zP=function(a,b){w.uri.L.LL(a);w.P.sM(a)&&(a=a.substr(0,a.length-1));w.P.SN(b)&&(b=b.substr(1));return w.P.OL(a,"/",b)};w.uri.L.mN=function(a){return w.uri.L.PN(a)};function Ca(a){la.call(this);this.headers=new ya;this.tB=a||l}w.e(Ca,la);Ca.gH="Content-Type";Ca.EL=/^https?$/i;Ca.BL="application/x-www-form-urlencoded;charset=utf-8";Ca.VF=[];Ca.send=function(a,b,c,e,f,h){var j=new Ca;Ca.VF.push(j);b&&w.w.Va(j,"complete",b);w.w.Va(j,"ready",w.uK(Ca.RL,j));h&&(j.KG=Math.max(0,h));j.send(a,c,e,f)};Ca.TP=function(){for(var a=Ca.VF;a.length;)a.pop().kj()};Ca.fR=function(a){Ca.prototype.zv=a.zK(Ca.prototype.zv)};Ca.RL=function(a){a.kj();w.T.remove(Ca.VF,a)};v=Ca.prototype;
v.Lm=n;v.Hc=l;v.sB=l;v.SJ="";v.eD=n;v.Ty=n;v.kE=n;v.jp=n;v.KG=0;v.yq=l;v.JK="";v.VG=n;
v.send=function(a,b,c,e){this.Hc&&d(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.SJ=a;this.eD=n;this.Lm=i;this.Hc=this.tB?this.tB.uC():w.zj.ck();this.sB=this.tB?this.tB.Hu():w.zj.ck.Hu();this.Hc.onreadystatechange=w.bind(this.tK,this);try{this.kE=i,this.Hc.open(b,a,i),this.kE=n}catch(f){Da(this);return}var a=c||"",h=this.headers.la();e&&w.Ed.forEach(e,function(a,b){h.set(b,a)});"POST"==b&&!h.pk(Ca.gH)&&h.set(Ca.gH,Ca.BL);w.Ed.forEach(h,function(a,
b){this.Hc.setRequestHeader(b,a)},this);this.JK&&(this.Hc.responseType=this.JK);w.object.pk(this.Hc,"withCredentials")&&(this.Hc.withCredentials=this.VG);try{this.yq&&(ma.clearTimeout(this.yq),this.yq=l),0<this.KG&&(this.yq=ma.setTimeout(w.bind(this.UN,this),this.KG)),this.Ty=i,this.Hc.send(a),this.Ty=n}catch(j){Da(this)}};v.UN=function(){"undefined"!=typeof w&&this.Hc&&(this.dispatchEvent("timeout"),this.abort(8))};function Da(a){a.Lm=n;a.Hc&&(a.jp=i,a.Hc.abort(),a.jp=n);Ea(a);Fa(a)}
function Ea(a){a.eD||(a.eD=i,a.dispatchEvent("complete"),a.dispatchEvent("error"))}v.abort=function(){this.Hc&&this.Lm&&(this.Lm=n,this.jp=i,this.Hc.abort(),this.jp=n,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Fa(this))};v.cn=function(){this.Hc&&(this.Lm&&(this.Lm=n,this.jp=i,this.Hc.abort(),this.jp=n),Fa(this,i));Ca.b.cn.call(this)};v.tK=function(){!this.kE&&!this.Ty&&!this.jp?this.zv():Ga(this)};v.zv=function(){Ga(this)};
function Ga(a){if(a.Lm&&"undefined"!=typeof w&&(!a.sB[1]||!(4==(a.Hc?a.Hc.readyState:0)&&2==Ha(a))))if(a.Ty&&4==(a.Hc?a.Hc.readyState:0))ma.setTimeout(w.bind(a.tK,a),0);else if(a.dispatchEvent("readystatechange"),4==(a.Hc?a.Hc.readyState:0)){a.Lm=n;var b=Ha(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 304:case 1223:c=i;break a;default:c=n}if(!c){if(b=0===b)b=w.uri.L.FM(""+a.SJ),b=!Ca.EL.test(b);c=b}c?(a.dispatchEvent("complete"),a.dispatchEvent("success")):Ea(a);Fa(a)}}
function Fa(a,b){if(a.Hc){var c=a.Hc,e=a.sB[0]?w.lK:l;a.Hc=l;a.sB=l;a.yq&&(ma.clearTimeout(a.yq),a.yq=l);b||a.dispatchEvent("ready");try{c.onreadystatechange=e}catch(f){}}}function Ha(a){try{return 2<(a.Hc?a.Hc.readyState:0)?a.Hc.status:-1}catch(b){return-1}}w.debug.Ye.EK(function(a){Ca.prototype.zv=a(Ca.prototype.zv)});function Ia(a){a=typeof a;return"string"==a||"number"==a||"boolean"==a}function Ja(a){return"string"!=typeof a&&"undefined"!=typeof a.length}
function Ka(a,b){var c="<"+a;"undefined"!=typeof b.functionName&&(b["function"]=b.functionName,delete b.functionName);for(var e in b)"format"!=e&&"text"!=e&&"custom_attribute_value"!=e&&"attr"!=e&&Ia(b[e])&&(c+=" "+e+'="'+b[e]+'"');c+=">";for(e in b)if("arg"==e&&Ja(b[e]))for(var f=b[e],h=0;h<f.length;h++)c+="<arg><![CDATA["+f[h]+"]]\></arg>";else if("custom_attribute_value"==e||"attr"==e)c+="<![CDATA["+b[e]+"]]\>";else if("format"==e||"text"==e)c+="<"+e+"><![CDATA["+b[e]+"]]\></"+e+">";else if(Ja(b[e])){f=
b[e];for(h=0;h<f.length;h++)c+=Ka(e,f[h])}else Ia(b[e])||(c+=Ka(e,b[e]));return c+("</"+a+">")}function La(){}v=La.prototype;v.ha=l;v.r=l;v.on=l;v.Mz=l;v.Lz=l;v.iK=l;v.mF=l;v.ly=l;v.kp=function(a){this.ha=a;this.mF=this.iK=this.Lz=this.Mz=this.Wl=n;this.hi=this.ha.enableFirefoxPrintPreviewFix};v.Wl=n;v.oK=function(){this.Wl=i;this.Mz&&this.Pi(this.ha.xmlFile);this.Lz&&this.Th(this.ha.xmlData);this.iK&&this.jo(this.ha.jsonFile);this.mF&&this.Nj(this.ha.jsonData)};v.pK=function(){this.hi&&Ma(this)};
v.Uc=t(l);v.Qu=function(){this.ha.visible=n;this.r&&(this.r.style.visibility="hidden",this.r.setAttribute("width","1px"),this.r.setAttribute("height","1px"))};v.show=function(){this.ha.visible=i;this.r&&(this.r.style.visibility="visible",this.r.setAttribute("width",this.Ia+""),this.r.setAttribute("height",this.ab+""))};
v.jr=function(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Wr&&z.platform.Bp?(a.style.display="none",function(){4==a.readyState?(z.platform.Rk&&b!=l&&z.mu(window[b]),z.mu(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))};v.mu=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};v.Go=function(){return z.platform.fE&&this.ha.swfFile!=l};
v.write=function(a){var b=this.ha.width+"",c=this.ha.height+"",e=this.ha.preloaderSWFFile?this.ha.preloaderSWFFile:this.ha.swfFile;if(this.hi=this.hi&&z.platform.vJ)this.ly=new Na;if(z.platform.Wr&&z.platform.Bp){var f;f='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+(' id="'+this.ha.id+'"');f=f+(' width="'+b+'"')+(' height="'+c+'"')+(' style="visibility:'+(this.ha.visible?"visible":"hidden")+'"');f+=' codebase="'+z.platform.protocol+'//fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">';
f+=Oa("movie",e);f+=Oa("bgcolor",this.ha.bgColor);f+=Oa("allowScriptAccess","always");f+=Oa("flashvars",Pa(this));this.ha.wMode!=l&&(f+=Oa("wmode",this.ha.wMode));f+="</object>";if(z.platform.Rk){b=l;for(c=a;c;){if(c.nodeName!=l&&"form"==c.nodeName.toLowerCase()){b=c;break}c=c.parentNode}if(b!=l){window[this.ha.id]={};window[this.ha.id].FL=o();a.innerHTML=f;window[this.ha.id].FL=l;var a={},h;for(h in window[this.ha.id])"function"==typeof window[this.ha.id][h]&&(a[h]=window[this.ha.id][h]);this.r=
window[this.ha.id]=b[this.ha.id];this.ha.flashObject=this.r;for(h in a)Qa(h)}else a.innerHTML=f,this.r=document.getElementById(this.ha.id),this.ha.flashObject=this.r}else a.innerHTML=f,this.r=document.getElementById(this.ha.id),this.ha.flashObject=this.r}else{h=document.createElement("object");h.setAttribute("type","application/x-shockwave-flash");h.setAttribute("id",this.ha.id);h.setAttribute("width",b);h.setAttribute("height",c);h.setAttribute("data",e);h.setAttribute("style","visibility: "+(this.ha.visible?
"visible":"hidden"));Ra(h,"movie",e);Ra(h,"bgcolor",this.ha.bgColor);Ra(h,"allowScriptAccess","always");Ra(h,"flashvars",Pa(this));this.ha.wMode!=l&&Ra(h,"wmode",this.ha.wMode);if(a.hasChildNodes())for(;0<a.childNodes.length;)a.removeChild(a.firstChild);this.r=a.appendChild(h);this.ha.flashObject=this.r;this.on=a}return this.r!=l};function Oa(a,b){return'<param name="'+a+'" value="'+b+'" />'}
function Ra(a,b,c){var e=document.createElement("param");e.setAttribute("name",b);e.setAttribute("value",c);a.appendChild(e)}function Qa(a){eval('obj[functionName] = function(){return eval(this.CallFunction("<invoke name=\\"'+a+'\\" returntype=\\"javascript\\">" + __flash__argumentsToXML(arguments,0) + "</invoke>"));}')}
function Pa(a){var b="__externalobjid="+a.ha.id;a.ha.preloaderSWFFile&&(b+="&swffile="+a.ha.swfFile);a.ha.xmlFile&&(b+="&xmlfile="+a.ha.xmlFile);a.ha.enabledChartEvents&&(b+="&__enableevents=1");a.ha.enabledChartMouseEvents&&(b+="&__enablechartmouseevents=1");b+="&preloaderInit="+a.ha.messages.preloaderInit;b+="&preloaderLoading="+a.ha.messages.preloaderLoading;b+="&init="+a.ha.messages.init;b+="&loadingConfig="+a.ha.messages.loadingConfig;b+="&loadingTemplates="+a.ha.messages.loadingTemplates;b+=
"&loadingResources="+a.ha.messages.loadingResources;b+="&noData="+a.ha.messages.noData;return b+="&waitingForData="+a.ha.messages.waitingForData}v.Ht=t(i);v.gB=function(){(this.hi||this.on)&&this.ly.kj();Ma(this)};v.pq=function(a,b){this.r&&(this.r.setAttribute("width",a+""),this.r.setAttribute("height",b+""))};
v.remove=function(){this.r&&(this.r.Dispose&&this.r.Dispose(),Sa(this.r,this.Dn),this.hi&&(this.hi||this.on)&&this.ly.kj());this.r=l;this.ha.flashObject=this.r;if(z&&z.TM())for(var a=z.RI(),b=0;b<a;b++)if(z.II()[b]==this){z.II().splice(b,1);break}z&&z.JI()&&this.Dn!=l&&(z.JI()[this.Dn]=l)};v.clear=function(){this.r&&this.r.Clear&&this.r.Clear()};v.refresh=function(){this.r!=l&&this.r.Refresh!=l&&this.r.Refresh()};v.Ys=function(a,b){this.r!=l&&this.r.UpdateData!=l&&this.r.UpdateData(a,b)};
v.vA=function(a){this.r&&this.r.SetLoading&&this.r.SetLoading(a)};v.qy=function(){return this.r.GetInformation()};v.Pi=function(a){this.r&&this.Wl?this.r.SetXMLDataFromURL(a):this.Mz=i};v.Th=function(a){this.r&&this.Wl?this.r.SetXMLDataFromString(a):this.Lz=i};v.jo=o();v.Nj=function(a){this.r&&this.Wl?this.Th(Ka("anychart",a)):this.mF=i};v.hw=function(a){this.r&&this.Wl?this.r.SetXMLDataFromString(a):this.Lz=i};v.DA=function(a){this.r&&this.Wl?this.r.SetXMLDataFromURL(a):this.Mz=i};
v.qq=function(a,b){this.r&&this.Wl&&this.r.UpdateViewFromURL(a,b)};v.zA=function(a,b){this.r&&this.Wl&&this.r.UpdateViewFromString(a,b)};v.md=function(a,b){this.r!=l&&this.r.AddPoint!=l&&this.r.AddPoint(a,b)};v.dk=function(a,b,c){this.r!=l&&this.r.AddPointAt!=l&&this.r.AddPointAt(a,b,c)};v.Yk=function(a,b){this.r!=l&&this.r.RemovePoint!=l&&this.r.RemovePoint(a,b)};v.kl=function(a,b,c){this.r!=l&&this.r.UpdatePoint!=l&&this.r.UpdatePoint(a,b,c)};
v.$j=function(a,b,c){this.r!=l&&this.r.UpdatePointData!=l&&this.r.UpdatePointData(a,b,c)};v.Ck=function(a,b,c){this.r!=l&&this.r.HighlightPoint!=l&&this.r.HighlightPoint(a,b,c)};v.Jj=function(a,b,c){this.r!=l&&this.r.SelectPoint!=l&&this.r.SelectPoint(a,b,c)};v.fB=function(a,b,c,e){this.r&&this.r.updatePointWithAnimation!=l&&this.r.updatePointWithAnimation(a,b,c,e)};v.OA=function(){this.r&&this.r.startPointsUpdate!=l&&this.r.startPointsUpdate()};v.ek=function(a){this.r!=l&&this.r.AddSeries!=l&&this.r.AddSeries(a)};
v.fk=function(a,b){this.r!=l&&this.r.AddSeriesAt!=l&&this.r.AddSeriesAt(a,b)};v.Zk=function(a){this.r!=l&&this.r.RemoveSeries!=l&&this.r.RemoveSeries(a)};v.ll=function(a,b){this.r!=l&&this.r.UpdateSeries!=l&&this.r.UpdateSeries(a,b)};v.el=function(a,b){this.r!=l&&this.r.ShowSeries!=l&&this.r.ShowSeries(a,b)};v.Dk=function(a,b){this.r!=l&&this.r.HighlightSeries!=l&&this.r.HighlightSeries(a,b)};v.Bk=function(a,b){this.r!=l&&this.r.HighlightCategory!=l&&this.r.HighlightCategory(a,b)};
v.KA=function(a,b){this.r!=l&&this.r.ShowAxisMarker!=l&&this.r.ShowAxisMarker(a,b)};v.bl=function(a,b){this.r!=l&&this.r.SetPlotCustomAttribute!=l&&this.r.SetPlotCustomAttribute(a,b)};v.ot=function(a,b,c){this.r!=l&&this.r.View_SetPlotCustomAttribute!=l&&this.r.View_SetPlotCustomAttribute(a,b,c)};v.ft=function(a,b){this.r!=l&&this.r.View_AddSeries!=l&&this.r.View_AddSeries(a,b)};v.mt=function(a,b){this.r!=l&&this.r.View_RemoveSeries!=l&&this.r.View_RemoveSeries(a,b)};
v.gt=function(a,b,c){this.r!=l&&this.r.View_AddSeriesAt!=l&&this.r.View_AddSeriesAt(a,b,c)};v.rt=function(a,b,c){this.r!=l&&this.r.View_UpdateSeries!=l&&this.r.View_UpdateSeries(a,b,c)};v.pt=function(a,b,c){this.r!=l&&this.r.View_ShowSeries!=l&&this.r.View_ShowSeries(a,b,c)};v.dt=function(a,b,c){this.r!=l&&this.r.View_AddPoint!=l&&this.r.View_AddPoint(a,b,c)};v.et=function(a,b,c,e){this.r!=l&&this.r.View_AddPointAt!=l&&this.r.View_AddPointAt(a,b,c,e)};
v.lt=function(a,b,c){this.r!=l&&this.r.View_RemovePoint!=l&&this.r.View_RemovePoint(a,b,c)};v.qt=function(a,b,c,e){this.r!=l&&this.r.View_UpdatePoint!=l&&this.r.View_UpdatePoint(a,b,c,e)};v.pB=function(a){this.r!=l&&this.r.View_Clear!=l&&this.r.View_Clear(a)};v.kt=function(a){this.r!=l&&this.r.View_Refresh!=l&&this.r.View_Refresh(a)};v.jt=function(a,b,c){this.r!=l&&this.r.View_HighlightSeries!=l&&this.r.View_HighlightSeries(a,b,c)};
v.it=function(a,b,c,e){this.r!=l&&this.r.View_HighlightPoint!=l&&this.r.View_HighlightPoint(a,b,c,e)};v.ht=function(a,b,c){this.r!=l&&this.r.View_HighlightCategory!=l&&this.r.View_HighlightCategory(a,b,c)};v.nt=function(a,b,c,e){this.r!=l&&this.r.View_SelectPoint!=l&&this.r.View_SelectPoint(a,b,c,e)};v.$s=function(a,b,c,e){this.r!=l&&this.r.UpdateViewPointData!=l&&this.r.UpdateViewPointData(a,b,c,e)};v.Er=function(a,b){return this.r.GetPngScreen(a,b)};
v.Ey=function(a,b){return this.r.GetPdfScreen(a,b)};v.aA=function(){this.r.PrintChart()};v.mA=function(a,b){this.r.SaveAsImage(a,b)};v.nA=function(a,b){this.r.SaveAsPDF(a,b)};v.oA=function(a){this.r!=l&&this.r.ScrollXTo!=l&&this.r.ScrollXTo(a)};v.pA=function(a){this.r!=l&&this.r.ScrollYTo!=l&&this.r.ScrollYTo(a)};v.scrollTo=function(a,b){this.r!=l&&this.r.ScrollTo!=l&&this.r.ScrollTo(a,b)};v.mB=function(a,b){this.r!=l&&this.r.ViewScrollXTo!=l&&this.r.ViewScrollXTo(a,b)};
v.nB=function(a,b){this.r!=l&&this.r.ViewScrollYTo!=l&&this.r.ViewScrollYTo(a,b)};v.Ky=function(){return this.r!=l&&this.r.GetXScrollInfo!=l?this.r.GetXScrollInfo():l};v.Ly=function(){return this.r!=l&&this.r.GetYScrollInfo!=l?this.r.GetYScrollInfo():l};v.Iy=function(a){if(this.r!=l&&this.r.GetViewXScrollInfo!=l)return this.r.GetViewXScrollInfo(a)};v.Jy=function(a){if(this.r!=l&&this.r.GetViewYScrollInfo!=l)return this.r.GetViewYScrollInfo(a)};v.EA=function(a){this.r!=l&&this.r.SetXZoom!=l&&this.r.SetXZoom(a)};
v.FA=function(a){this.r!=l&&this.r.SetYZoom!=l&&this.r.SetYZoom(a)};v.GA=function(a,b){this.r!=l&&this.r.SetZoom!=l&&this.r.SetZoom(a,b)};v.AA=function(a,b){this.r!=l&&this.r.SetViewXZoom!=l&&this.r.SetViewXZoom(a,b)};v.BA=function(a,b){this.r!=l&&this.r.SetViewYZoom!=l&&this.r.SetViewYZoom(a,b)};v.CA=function(a,b,c){this.r!=l&&this.r.SetViewZoom!=l&&this.r.SetViewZoom(a,b,c)};v.$w=function(){this.r!=l&&this.r.RepeatAnimation!=l&&this.r.RepeatAnimation()};
function Sa(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Wr&&z.platform.Bp?(a.style.display="none",function(){4==a.readyState?(z.platform.Rk&&b&&this.mu(window[b]),z.mu(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))}v.mu=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};
function Ma(a){if(a.hi&&a.on){var b=a.Er();if(b&&0!=b.length){var c=a.on.getAttribute("id");c||(c="__chart_generated_container__"+a.Dn,a.on.setAttribute("id",c));var e=a.ly,f=a.on,h=a.Ia+"",j=a.ab+"",a=a.on.nodeName,k=document.getElementsByTagName("head");if(k=0<k.length?k[0]:l){var m;m=k;var r=document.createElement("style");r.setAttribute("type","text/css");r.setAttribute("media","screen");var s=a+"#"+c,u=s+" img";r.appendChild(document.createTextNode(s+(" object { width:"+h+"; height:"+j+";padding:0; margin:0; }\n")));
r.appendChild(document.createTextNode(u+" { display: none; }"));m=m.appendChild(r);e.ru=m;m=document.createElement("style");m.setAttribute("type","text/css");m.setAttribute("media","print");a=a+"#"+c;c=a+" img";h=" { display: block; width: "+h+"; height: "+j+"; }";m.appendChild(document.createTextNode(a+" object { display: none; }\n"));m.appendChild(document.createTextNode(c+h));h=k.appendChild(m);e.su=h;h=document.createElement("img");h=f.appendChild(h);h.src="data:image/png;base64,"+b;e.qu=h}}}}
function Na(){}v.ru=l;v.su=l;v.qu=l;Na.prototype.kj=function(){this.qu&&this.qu.parentNode&&this.qu.parentNode.removeChild(this.qu);this.ru&&(this.ru.parentNode.removeChild(this.ru),this.ru=l);this.su&&(this.su.parentNode.removeChild(this.su),this.su=l)};w.Rg("anychart.scope.goog",w);w.Rg("anychart.scope.Event",ha);w.Rg("anychart.scope.EventTarget",la);w.Rg("anychart.scope.EventType",y);w.Rg("anychart.scope.XhrIo",Ca);var Ta={};w.Rg("anychart.WMode",Ta);w.Q(Ta,"WINDOW","window");w.Q(Ta,"TRANSPARENT","transparent");w.Q(Ta,"OPAQUE","opaque");var Ua={};w.Rg("anychart.RenderingType",Ua);w.Q(Ua,"FLASH_ONLY","flash");w.Q(Ua,"SVG_ONLY","svg");w.Q(Ua,"FLASH_PREFERRED","flashPreferred");w.Q(Ua,"SVG_PREFERRED","svgPreferred");
function z(a,b,c){c&&(this.id=c);this.swfFile=z.swfFile;this.preloaderSWFFile=z.preloaderSWFFile;this.width=z.width;this.height=z.height;this.enableFirefoxPrintPreviewFix=z.enableFirefoxPrintPreviewFix;this.enabledChartEvents=z.enabledChartEvents;this.enabledChartMouseEvents=z.enabledChartMouseEvents;this.renderingType=z.renderingType;this.watermark=z.watermark;this.messages.preloaderInit=z.messages.preloaderInit;this.messages.preloaderLoading=z.messages.preloaderLoading;this.messages.init=z.messages.init;
this.messages.loadingConfig=z.messages.loadingConfig;this.messages.loadingResources=z.messages.loadingResources;this.messages.loadingTemplates=z.messages.loadingTemplates;this.messages.noData=z.messages.noData;this.messages.waitingForData=z.messages.waitingForData;a&&(this.swfFile=a);b&&(this.preloaderSWFFile=b);this.ce={};z.FN(this)}w.Rg("AnyChart",z);z.VERSION="6.0.11 (build #36916)";w.Q(z,"VERSION",z.VERSION);z.width=550;w.Q(z,"width",z.width);z.height=400;w.Q(z,"height",z.height);z.PF="flash";
w.Q(z,"renderingType",z.PF);z.ZC=i;w.Q(z,"enabledChartEvents",z.ZC);z.$C=n;w.Q(z,"enabledChartMouseEvents",z.$C);z.IG=l;w.Q(z,"swfFile",z.IG);z.MF=l;w.Q(z,"preloaderSWFFile",z.MF);z.hi=i;w.Q(z,"enableFirefoxPrintPreviewFix",z.hi);z.prototype.id=l;w.Q(z.prototype,"id",z.prototype.id);z.Lt=[];z.TM=function(){return z.Lt&&0<z.RI()};z.RI=function(){return z.Lt.length};z.II=function(){return z.Lt};z.$q={};z.JI=function(){return z.$q};z.prototype.PF=l;w.Q(z.prototype,"renderingType",z.prototype.PF);
z.prototype.pa=l;z.prototype.Hk=n;z.prototype.mO=l;w.Q(z.prototype,"xmlFile",z.prototype.mO);z.prototype.hN=l;w.Q(z.prototype,"jsonFile",z.prototype.hN);z.prototype.lO=l;w.Q(z.prototype,"xmlData",z.prototype.lO);z.prototype.gN=l;w.Q(z.prototype,"jsonData",z.prototype.gN);z.prototype.width=l;w.Q(z.prototype,"width",z.prototype.width);z.prototype.height=l;w.Q(z.prototype,"height",z.prototype.height);z.prototype.iO=l;w.Q(z.prototype,"watermark",z.prototype.iO);z.prototype.IG=l;
w.Q(z.prototype,"swfFile",z.prototype.IG);z.prototype.MF=l;w.Q(z.prototype,"preloaderSWFFile",z.prototype.MF);z.prototype.hi=i;w.Q(z.prototype,"enableFirefoxPrintPreviewFix",z.prototype.hi);z.prototype.hO=l;w.Q(z.prototype,"wMode",z.prototype.hO);z.prototype.ZC=i;w.Q(z.prototype,"enabledChartEvents",z.prototype.ZC);z.prototype.$C=n;w.Q(z.prototype,"enabledChartMouseEvents",z.prototype.$C);z.prototype.ce=l;z.prototype.bgColor="#FFFFFF";w.Q(z.prototype,"bgColor",z.prototype.bgColor);
z.prototype.gO=i;w.Q(z.prototype,"visible",z.prototype.gO);z.prototype.show=function(){this.visible=i;this.pa.show()};w.Q(z.prototype,"show",z.prototype.show);z.prototype.Qu=function(){this.visible=n;this.pa.Qu()};w.Q(z.prototype,"hide",z.prototype.Qu);z.L={};z.L.eE=function(a){return"undefined"!=typeof a};z.L.push=function(a,b){a[a.length]=b};var Va=navigator&&navigator.userAgent?navigator.userAgent.toLowerCase():l,Wa=navigator&&navigator.platform?navigator.platform.toLowerCase():l;z.platform={};
w.Q(z,"platform",z.platform);z.platform.Bp=Wa?/win/.test(Wa):/win/.test(Va);w.Q(z.platform,"isWin",z.platform.Bp);z.platform.cN=!z.platform.Bp&&(Wa?/mac/.test(Wa):/mac/.test(Va));w.Q(z.platform,"isMac",z.platform.cN);z.platform.eJ="undefined"!=typeof document.getElementById&&"undefined"!=typeof document.getElementsByTagName&&"undefiend"!=typeof document.createElement;w.Q(z.platform,"hasDom",z.platform.eJ);z.platform.rL=/webkit/.test(Va)?parseFloat(Va.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):n;
w.Q(z.platform,"webKit",z.platform.rL);z.platform.Wr=/msie/.test(Va);w.Q(z.platform,"isIE",z.platform.Wr);z.platform.vJ=/firefox/.test(Va);w.Q(z.platform,"isFirefox",z.platform.vJ);z.platform.protocol="https:"==location.protocol?"https:":"http:";w.Q(z.platform,"protocol",z.platform.protocol);
z.wJ=function(){z.platform.pi=[0,0,0];var a;if(navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((a=navigator.plugins["Shockwave Flash"].description)&&(!navigator.mimeTypes||!navigator.mimeTypes[["application/x-shockwave-flash"]]||navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))a=a.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),z.platform.pi[0]=parseInt(a.replace(/^(.*)\..*$/,"$1"),10),z.platform.pi[1]=parseInt(a.replace(/^.*\.(.*)\s.*$/,"$1"),10),z.platform.pi[2]=
/[a-zA-Z]/.test(a)?parseInt(a.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof window.ActiveXObject)try{var b=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(b&&(a=b.GetVariable("$version")))a=a.split(" ")[1].split(","),z.platform.pi=[parseInt(a[0],10),parseInt(a[1],10),parseInt(a[2],10)]}catch(c){}return z.platform.pi!=l&&9<=Number(z.platform.pi[0])};w.Q(z,"isFlashPlayerValidVersion",z.wJ);z.platform.fE=z.wJ();w.Q(z.platform,"hasRequiredVersion",z.platform.fE);
z.platform.pi=z.platform.pi;w.Q(z.platform,"flashPlayerVersion",z.platform.pi);z.platform.Rk=z.platform.fE&&z.platform.Wr&&z.platform.Bp;w.Q(z.platform,"needFormFix",z.platform.Rk);z.platform.Rk&&(z.platform.Rk=9==Number(z.platform.pi[0]),z.platform.Rk=z.platform.Rk&&0==Number(z.platform.pi[1]),z.platform.Rk=z.platform.Rk&&115>Number(z.platform.pi[2]));z.cD=[];z.CN=function(a){w.ez(a)&&z.cD.push(a)};w.Q(z,"ready",z.CN);
z.jN=function(a){if(a==l||a==g)a=z.zM();var a=a+"AnyChartHTML5.js",b=new Ca;b.VG=i;w.w.Va(b,"complete",z.sK,l,z);w.w.Va(b,["error","abort"],z.rK,l,z);b.send(a,"GET",l,"anychart.com")};w.Q(z,"loadHTML5Engine",z.jN);z.sK=function(a){var a=a.target,b;try{b=a.Hc?a.Hc.responseText:""}catch(c){b=""}eval(b.toString());b=z.cD.length;for(var e=0;e<b;e++)z.cD[e]();z.eM(a)};z.rK=function(){d(Error("Can not find AnyChart html5 engine in JS folder."))};
z.eM=function(a){w.w.bc(a,"complete",z.sK,l,z);w.w.bc(a,["error","abort"],z.rK,l,z)};z.zM=function(){for(var a=w.global.document.getElementsByTagName("script"),b=a.length-1;b>=0;--b){var c=a[b].src,e=c.lastIndexOf("?"),e=e==-1?c.length:e,c=c.substr(0,e),f=c.split("/"),f=f[f.length-1].toLowerCase(),h=f.length;if(f.indexOf("anychart")!=-1&&f.substr(h-3,3)==".js")return c.substr(0,e-h)}return l};z.L.attachEvent=function(a,b,c){a.attachEvent(b,c);z.L.push(z.L.UQ,[a,b,c])};
z.L.HL=function(a,b){if(z.L.eE(window.addEventListener))window.addEventListener(a,b,n);else if(z.L.eE(document.addEventListener))document.addEventListener(a,b,n);else if(z.L.eE(window.attachEvent))z.L.attachEvent(window,"on"+a,b);else if(typeof window["on"+a]=="function"){var c=window["on"+a];window["on"+a]=function(){c();b()}}else window["on"+a]=b};w.Rg("AnyChart.utils.addGlobalEventListener",z.L.HL);z.L.Tr=n;z.L.OC=[];z.L.GL=function(a){z.L.Tr?a():z.L.OC.push(a)};
z.L.nr=function(){if(!z.L.Tr){try{var a=document.getElementsByTagName("body")[0].appendChild(document.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}z.L.Tr=i;for(var a=z.L.OC.length,c=0;c<a;c++)z.L.OC[c]()}};
z.L.EN=function(){if(z.platform.eJ){typeof document.readyState!="undefined"&&(document.readyState=="complete"||document.getElementsByTagName("body")[0]||document.body)&&z.L.nr();if(!z.L.Tr){document.addEventListener&&document.addEventListener("DOMContentLoaded",z.L.nr,n);if(z.platform.Wr&&z.platform.Bp){document.attachEvent("onreadystatechange",function(){if(document.readyState=="complete"){document.detachEvent("onreadystatechange",arguments.callee);z.L.nr()}});window==top&&function(){if(!z.L.Tr){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}z.L.nr()}}()}z.platform.rL&&function(){z.L.Tr||(/loaded|complete/.test(document.readyState)?z.L.nr():setTimeout(arguments.callee,0))}();w.w.Va(window,"load",z.L.nr)}}};z.L.EN();z.dispatchEvent=function(a,b){z.AH(a)&&b!=l&&z.$q[a].dispatchEvent(b)};w.Q(z,"dispatchEvent",z.dispatchEvent);
function Xa(a){switch(a.renderingType){case "svg":return new window.anychart.render.svg.SVGRenderer;case "flash":return new La;default:case "flashPreferred":return z.platform.hasRequiredVersion?new La:new window.anychart.render.svg.SVGRenderer;case "svgPreferred":return window.SVGAngle!=g?new window.anychart.render.svg.SVGRenderer:new La}}z.FN=function(a){a.id=a.id==g?"__AnyChart___"+z.Lt.length:a.id;z.$q[a.id]=a;z.Lt.push(a)};z.AH=function(a){return a&&z.$q&&z.$q[a]};
z.BM=function(a){return z.AH(a)?z.$q[a]:l};w.Q(z,"getChartById",z.BM);z.mM=function(a,b){z.jr(a,b)};w.Q(z,"disposeFlashObject",z.mM);z.jr=function(a,b){a.jr(a,b)};w.Q(z,"disposeVisual",z.jr);z.prototype.jr=function(a,b){this.pa.jr(a,b)};z.L.qf={};w.Rg("AnyChart.utils.JSConverter",z.L.qf);z.L.qf.BE=function(a){a=typeof a;return a=="string"||a=="number"||a=="boolean"};w.Q(z.L.qf,"isAttribute",z.L.qf.BE);z.L.qf.isArray=function(a){return typeof a!="string"&&typeof a.length!="undefined"};
w.Q(z.L.qf,"isArray",z.L.qf.isArray);z.L.qf.VL=function(a){return z.L.qf.vC("anychart",a)};w.Q(z.L.qf,"convert",z.L.qf.VL);
z.L.qf.vC=function(a,b){var c,e,f="<"+a;if(typeof b.functionName!="undefined"){b["function"]=b.functionName;delete b.functionName}for(c in b)c!="format"&&c!="text"&&c!="custom_attribute_value"&&c!="attr"&&z.L.qf.BE(b[c])&&(f=f+(" "+c+'="'+b[c]+'"'));f=f+">";for(c in b)if(c=="arg"&&z.L.qf.isArray(b[c])){var h=b[c];for(e=0;e<h.length;e++)f=f+("<arg><![CDATA["+h[e]+"]]\></arg>")}else if(c=="custom_attribute_value"||c=="attr")f=f+("<![CDATA["+b[c]+"]]\>");else if(c=="format"||c=="text")f=f+("<"+c+"><![CDATA["+
b[c]+"]]\></"+c+">");else if(z.L.qf.isArray(b[c])){h=b[c];for(e=0;e<h.length;e++)f=f+z.L.qf.vC(c,h[e])}else z.L.qf.BE(b[c])||(f=f+z.L.qf.vC(c,b[c]));return f+("</"+a+">")};z.messages={};z.messages.preloaderInit=" ";z.messages.preloaderLoading="Loading... ";z.messages.init="Initializing...";z.messages.loadingConfig="Loading config...";z.messages.loadingResources="Loading resources...";z.messages.loadingTemplates="Loading templates...";z.messages.noData="No Data";z.messages.waitingForData="Waiting for data...";
z.watermark=l;z.prototype.oN={};w.Q(z.prototype,"messages",z.prototype.oN);z.prototype.messages.preloaderInit=l;z.prototype.messages.preloaderLoading=l;z.prototype.messages.init=l;z.prototype.messages.loadingConfig=l;z.prototype.messages.loadingResources=l;z.prototype.messages.loadingTemplates=l;z.prototype.messages.noData=l;z.prototype.messages.waitingForData=l;z.prototype.addEventListener=function(a,b){this.ce[a]==l&&(this.ce[a]=[]);this.ce[a].push(b)};w.Q(z.prototype,"addEventListener",z.prototype.addEventListener);
z.prototype.removeEventListener=function(a,b){if(!(this.ce==l||this.ce[a]==l)){for(var c=-1,e=0;e<this.ce[a].length;e++)if(this.ce[a][e]==b){c=e;break}c!=-1&&this.ce[a].splice(c,1)}};w.Q(z.prototype,"removeEventListener",z.prototype.removeEventListener);z.prototype.dispatchEvent=function(a){if(!(a==l||a.type==l)){a.type=="create"?this.pa.oK():a.type=="draw"&&this.pa.pK();a.target=this;if(!(this.ce==l||this.ce[a.type]==l))for(var b=this.ce[a.type].length,c=0;c<b;c++)this.ce[a.type][c](a)}};
w.Q(z.prototype,"dispatchEvent",z.prototype.dispatchEvent);z.prototype.Go=function(){return this.pa.Go()};w.Q(z.prototype,"canWrite",z.prototype.Go);z.prototype.write=function(a){this.pa=Xa(this);this.pa.kp(this);if(this.Go()){if(a==g){a="__chart_generated_container__"+this.id;document.write('<div id="'+a+'"></div>')}var b=this;z.L.GL(function(){typeof a=="string"?Ya(b,document.getElementById(a)):Ya(b,a)})}};w.Q(z.prototype,"write",z.prototype.write);
function Ya(a,b){a.Hk=a.pa.write(b);a.Hk&&a.Ht()&&(a.xmlFile!=l?a.Pi(a.xmlFile):a.jsonFile!=l?a.jo(a.jsonFile):a.xmlData!=l?a.hw(a.xmlData):a.jsonData!=l&&a.Nj(a.jsonData))}z.prototype.Ht=function(){return this.pa.Ht()};w.Q(z.prototype,"canSetConfigAfterWrite",z.prototype.Ht);z.prototype.gB=function(){this.pa.gB()};w.Q(z.prototype,"updatePrintForFirefox",z.prototype.gB);z.prototype.pq=function(a,b){this.width=a;this.height=b;this.pa.pq(a,b)};w.Q(z.prototype,"setSize",z.prototype.pq);
w.Rg("AnyChart.prototype.resize",z.prototype.pq);z.prototype.remove=function(){this.pa.remove()};w.Q(z.prototype,"remove",z.prototype.remove);z.prototype.clear=function(){this.pa.clear()};w.Q(z.prototype,"clear",z.prototype.clear);z.prototype.refresh=function(){this.pa.refresh()};w.Q(z.prototype,"refresh",z.prototype.refresh);z.prototype.Ys=function(a,b){this.pa.Ys(a,b)};w.Q(z.prototype,"updateData",z.prototype.Ys);z.prototype.vA=function(a){this.pa.vA(a)};w.Q(z.prototype,"setLoading",z.prototype.vA);
z.prototype.qy=function(){return this.pa.qy()};w.Q(z.prototype,"getInformation",z.prototype.qy);z.prototype.Pi=function(a){this.xmlFile=a;this.Hk&&this.pa.Pi(a)};w.Q(z.prototype,"setXMLFile",z.prototype.Pi);z.prototype.Th=function(a){this.xmlData=""+a;this.Hk&&this.pa.Th(this.xmlData)};w.Q(z.prototype,"setXMLData",z.prototype.Th);z.prototype.hw=function(a){this.Hk&&this.pa.hw(a)};w.Q(z.prototype,"setXMLDataFromString",z.prototype.hw);z.prototype.DA=function(a){this.Hk&&this.pa.DA(a)};
w.Q(z.prototype,"setXMLDataFromURL",z.prototype.DA);z.prototype.qq=function(a,b){this.pa.qq(a,b)};w.Q(z.prototype,"setViewXMLFile",z.prototype.qq);z.prototype.zA=function(a,b){this.pa.zA(a,b)};w.Q(z.prototype,"setViewData",z.prototype.zA);z.prototype.jo=function(a){this.jsonFile=a;this.Hk&&this.pa.jo(a)};w.Q(z.prototype,"setJSONFile",z.prototype.jo);z.prototype.Nj=function(a){this.jsonData=a;this.Hk&&this.pa.Nj(this.jsonData)};w.Q(z.prototype,"setJSONData",z.prototype.Nj);
w.Rg("AnyChart.prototype.setJSData",z.prototype.Nj);z.prototype.setData=function(a){if(a!=l){for(var b=""+a;b.charAt(0)==" "&&b.length>0;)b=b.substr(1);if(b.charAt(0)=="<"){this.xmlData=""+a;this.Hk&&this.pa.Th(this.xmlData)}else{this.jsonData=a;this.Hk&&this.pa.Nj(this.jsonData)}}};w.Q(z.prototype,"setData",z.prototype.setData);z.prototype.md=function(a,b){this.pa.md(a,b)};w.Q(z.prototype,"addPoint",z.prototype.md);z.prototype.dk=function(a,b,c){this.pa.dk(a,b,c)};w.Q(z.prototype,"addPointAt",z.prototype.dk);
z.prototype.Yk=function(a,b){this.pa.Yk(a,b)};w.Q(z.prototype,"removePoint",z.prototype.Yk);z.prototype.kl=function(a,b,c){this.pa.kl(a,b,c)};w.Q(z.prototype,"updatePoint",z.prototype.kl);z.prototype.$j=function(a,b,c){this.pa.$j(a,b,c)};w.Q(z.prototype,"updatePointData",z.prototype.$j);z.prototype.Ck=function(a,b,c){this.pa.Ck(a,b,c)};w.Q(z.prototype,"highlightPoint",z.prototype.Ck);z.prototype.Jj=function(a,b,c){this.pa.Jj(a,b,c)};w.Q(z.prototype,"selectPoint",z.prototype.Jj);
z.prototype.fB=function(a,b,c,e){this.pa.fB(a,b,c,e)};w.Q(z.prototype,"updatePointWithAnimation",z.prototype.fB);z.prototype.OA=function(){this.pa.OA()};w.Q(z.prototype,"startPointsAnimation",z.prototype.OA);z.prototype.ek=function(a){this.pa.ek(a)};w.Q(z.prototype,"addSeries",z.prototype.ek);z.prototype.fk=function(a,b){this.pa.fk(a,b)};w.Q(z.prototype,"addSeriesAt",z.prototype.fk);z.prototype.Zk=function(a){this.pa.Zk(a)};w.Q(z.prototype,"removeSeries",z.prototype.Zk);
z.prototype.ll=function(a,b){this.pa.ll(a,b)};w.Q(z.prototype,"updateSeries",z.prototype.ll);z.prototype.el=function(a,b){this.pa.el(a,b)};w.Q(z.prototype,"showSeries",z.prototype.el);z.prototype.Dk=function(a,b){this.pa.Dk(a,b)};w.Q(z.prototype,"highlightSeries",z.prototype.Dk);z.prototype.Bk=function(a,b){this.pa.Bk(a,b)};w.Q(z.prototype,"highlightCategory",z.prototype.Bk);z.prototype.KA=function(a,b){this.pa.KA(a,b)};w.Q(z.prototype,"showAxisMarker",z.prototype.KA);
z.prototype.bl=function(a,b){this.pa.bl(a,b)};w.Q(z.prototype,"setPlotCustomAttribute",z.prototype.bl);z.prototype.ot=function(a,b,c){this.pa.ot(a,b,c)};w.Q(z.prototype,"view_setPlotCustomAttribute",z.prototype.ot);z.prototype.ft=function(a,b){this.pa.ft(a,b)};w.Q(z.prototype,"view_addSeries",z.prototype.ft);z.prototype.mt=function(a,b){this.pa.mt(a,b)};w.Q(z.prototype,"view_removeSeries",z.prototype.mt);z.prototype.gt=function(a,b,c){this.pa.gt(a,b,c)};w.Q(z.prototype,"view_addSeriesAt",z.prototype.gt);
z.prototype.rt=function(a,b,c){this.pa.rt(a,b,c)};w.Q(z.prototype,"view_updateSeries",z.prototype.rt);z.prototype.pt=function(a,b,c){this.pa.pt(a,b,c)};w.Q(z.prototype,"view_showSeries",z.prototype.pt);z.prototype.dt=function(a,b,c){this.pa.dt(a,b,c)};w.Q(z.prototype,"view_addPoint",z.prototype.dt);z.prototype.et=function(a,b,c,e){this.pa.et(a,b,c,e)};w.Q(z.prototype,"view_addPointAt",z.prototype.et);z.prototype.lt=function(a,b,c){this.pa.lt(a,b,c)};w.Q(z.prototype,"view_removePoint",z.prototype.lt);
z.prototype.qt=function(a,b,c,e){this.pa.qt(a,b,c,e)};w.Q(z.prototype,"view_updatePoint",z.prototype.qt);z.prototype.pB=function(a){this.pa.pB(a)};w.Q(z.prototype,"view_clear",z.prototype.pB);z.prototype.kt=function(a){this.pa.kt(a)};w.Q(z.prototype,"view_refresh",z.prototype.kt);z.prototype.jt=function(a,b,c){this.pa.jt(a,b,c)};w.Q(z.prototype,"view_highlightSeries",z.prototype.jt);z.prototype.it=function(a,b,c,e){this.pa.it(a,b,c,e)};w.Q(z.prototype,"view_highlightPoint",z.prototype.it);
z.prototype.ht=function(a,b,c){this.pa.ht(a,b,c)};w.Q(z.prototype,"view_highlightCategory",z.prototype.ht);z.prototype.nt=function(a,b,c,e){this.pa.nt(a,b,c,e)};w.Q(z.prototype,"view_selectPoint",z.prototype.nt);z.prototype.$s=function(a,b,c,e){this.pa.$s(a,b,c,e)};w.Q(z.prototype,"updateViewPointData",z.prototype.$s);z.prototype.Er=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;return this.pa.Er(a,b)};w.Q(z.prototype,"getPNG",z.prototype.Er);w.Rg("AnyChart.prototype.getPNGImage",z.prototype.Er);
z.prototype.Ey=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;return this.pa.Ey(a,b)};w.Q(z.prototype,"getPDF",z.prototype.Ey);z.prototype.aA=function(){this.pa.aA()};w.Q(z.prototype,"printChart",z.prototype.aA);z.prototype.mA=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;this.pa.mA(a,b)};w.Q(z.prototype,"saveAsImage",z.prototype.mA);z.prototype.nA=function(a,b){if(a==l||a==g)a=NaN;if(b==l||b==g)b=NaN;this.pa.nA(a,b)};w.Q(z.prototype,"saveAsPDF",z.prototype.nA);z.prototype.oA=function(a){this.pa.oA(a)};
w.Q(z.prototype,"scrollXTo",z.prototype.oA);z.prototype.pA=function(a){this.pa.pA(a)};w.Q(z.prototype,"scrollYTo",z.prototype.pA);z.prototype.scrollTo=function(a,b){this.pa.scrollTo(a,b)};w.Q(z.prototype,"scrollTo",z.prototype.scrollTo);z.prototype.mB=function(a,b){this.pa.mB(a,b)};w.Q(z.prototype,"viewScrollXTo",z.prototype.mB);z.prototype.nB=function(a,b){this.pa.nB(a,b)};w.Q(z.prototype,"viewScrollYTo",z.prototype.nB);z.prototype.Ky=function(){return this.pa.Ky()};
w.Q(z.prototype,"getXScrollInfo",z.prototype.Ky);z.prototype.Ly=function(){return this.pa.Ly()};w.Q(z.prototype,"getYScrollInfo",z.prototype.Ly);z.prototype.Iy=function(a){return this.pa.Iy(a)};w.Q(z.prototype,"getViewXScrollInfo",z.prototype.Iy);z.prototype.Jy=function(a){return this.pa.Jy(a)};w.Q(z.prototype,"getViewYScrollInfo",z.prototype.Jy);z.prototype.EA=function(a){this.pa.EA(a)};w.Q(z.prototype,"setXZoom",z.prototype.EA);z.prototype.FA=function(a){this.pa.FA(a)};
w.Q(z.prototype,"setYZoom",z.prototype.FA);z.prototype.GA=function(a,b){this.pa.GA(a,b)};w.Q(z.prototype,"setZoom",z.prototype.GA);z.prototype.AA=function(a,b){this.pa.AA(a,b)};w.Q(z.prototype,"setViewXZoom",z.prototype.AA);z.prototype.BA=function(a,b){this.pa.BA(a,b)};w.Q(z.prototype,"setViewYZoom",z.prototype.BA);z.prototype.CA=function(a,b,c){this.pa.CA(a,b,c)};w.Q(z.prototype,"setViewZoom",z.prototype.CA);z.prototype.$w=function(){this.pa.$w()};w.Q(z.prototype,"animate",z.prototype.$w);
z.prototype.Uc=function(a){return this.pa.Uc(a)};w.Q(z.prototype,"getSVG",z.prototype.Uc);})()
